var mongoose = require('./mongodb');

Array.prototype.unique = function () {
    var a = this.concat();
    for (var i = 0; i < a.length; ++i) {
        for (var j = i + 1; j < a.length; ++j) {
            if (a[i] === a[j])
                a.splice(j--, 1);
        }
    }

    return a;
};

var pokemonRawData =
    [{
        id: 1,
        name: 'Bulbasaur',
        img: 'assets/images/pokemons/001.png',
        type: ['Grass', 'Poison'],
        candy: 'Bulbasaur Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Water', 'Ground', 'Rock', 'Grass', 'Fairy'],
        weaknesses:
        ['Fire',
            'Grass',
            'Poison',
            'Flying',
            'Bug',
            'Dragon',
            'Steel',
            'Ground',
            'Rock',
            'Ghost'],
        egg: 2,
        buddy: 3,
        next_evolution: [2, 3],
        prev_evolution: [],
        location: ''
    },
        {
            id: 2,
            name: 'Ivysaur',
            img: 'assets/images/pokemons/002.png',
            type: ['Grass', 'Poison'],
            candy: 'Bulbasaur Candy',
            candy_count: '25',
            immunes: [],
            strengths: ['Water', 'Ground', 'Rock', 'Grass', 'Fairy'],
            weaknesses:
            ['Fire',
                'Grass',
                'Poison',
                'Flying',
                'Bug',
                'Dragon',
                'Steel',
                'Ground',
                'Rock',
                'Ghost'],
            egg: 0,
            buddy: 3,
            next_evolution: [3],
            prev_evolution: [1],
            location: ''
        },
        {
            id: 3,
            name: 'Venusaur',
            img: 'assets/images/pokemons/003.png',
            type: ['Grass', 'Poison'],
            candy: 'Bulbasaur Candy',
            candy_count: '100',
            immunes: [],
            strengths: ['Water', 'Ground', 'Rock', 'Grass', 'Fairy'],
            weaknesses:
            ['Fire',
                'Grass',
                'Poison',
                'Flying',
                'Bug',
                'Dragon',
                'Steel',
                'Ground',
                'Rock',
                'Ghost'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [1, 2],
            location: ''
        },
        {
            id: 4,
            name: 'Charmander',
            img: 'assets/images/pokemons/004.png',
            type: ['Fire'],
            candy: 'Charmander Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Grass', 'Ice', 'Bug', 'Steel'],
            weaknesses: ['Fire', 'Water', 'Rock', 'Dragon'],
            egg: 2,
            buddy: 3,
            next_evolution: [5, 6],
            prev_evolution: [],
            location: ''
        },
        {
            id: 5,
            name: 'Charmeleon',
            img: 'assets/images/pokemons/005.png',
            type: ['Fire'],
            candy: 'Charmander Candy',
            candy_count: '25',
            immunes: [],
            strengths: ['Grass', 'Ice', 'Bug', 'Steel'],
            weaknesses: ['Fire', 'Water', 'Rock', 'Dragon'],
            egg: 0,
            buddy: 3,
            next_evolution: [6],
            prev_evolution: [4],
            location: ''
        },
        {
            id: 6,
            name: 'Charizard',
            img: 'assets/images/pokemons/006.png',
            type: ['Fire', 'Flying'],
            candy: 'Charmander Candy',
            candy_count: '100',
            immunes: [],
            strengths: ['Grass', 'Ice', 'Bug', 'Steel', 'Fighting'],
            weaknesses: ['Fire', 'Water', 'Rock', 'Dragon', 'Electric', 'Steel'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [4, 5],
            location: ''
        },
        {
            id: 7,
            name: 'Squirtle',
            img: 'assets/images/pokemons/007.png',
            type: ['Water'],
            candy: 'Squirtle Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock'],
            weaknesses: ['Water', 'Grass', 'Dragon'],
            egg: 2,
            buddy: 3,
            next_evolution: [8, 9],
            prev_evolution: [],
            location: ''
        },
        {
            id: 8,
            name: 'Wartortle',
            img: 'assets/images/pokemons/008.png',
            type: ['Water'],
            candy: 'Squirtle Candy',
            candy_count: '25',
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock'],
            weaknesses: ['Water', 'Grass', 'Dragon'],
            egg: 0,
            buddy: 3,
            next_evolution: [9],
            prev_evolution: [7],
            location: ''
        },
        {
            id: 9,
            name: 'Blastoise',
            img: 'assets/images/pokemons/009.png',
            type: ['Water'],
            candy: 'Squirtle Candy',
            candy_count: '100',
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock'],
            weaknesses: ['Water', 'Grass', 'Dragon'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [7, 8],
            location: ''
        },
        {
            id: 10,
            name: 'Caterpie',
            img: 'assets/images/pokemons/010.png',
            type: ['Bug'],
            candy: 'Caterpie Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Grass', 'Psychic', 'Dark'],
            weaknesses: ['Fire', 'Fighting', 'Poison', 'Flying', 'Ghost', 'Steel', 'Fairy'],
            egg: 2,
            buddy: 1,
            next_evolution: [11, 12],
            prev_evolution: [],
            location: ''
        },
        {
            id: 11,
            name: 'Metapod',
            img: 'assets/images/pokemons/011.png',
            type: ['Bug'],
            candy: 'Caterpie Candy',
            candy_count: '12',
            immunes: [],
            strengths: ['Grass', 'Psychic', 'Dark'],
            weaknesses: ['Fire', 'Fighting', 'Poison', 'Flying', 'Ghost', 'Steel', 'Fairy'],
            egg: 0,
            buddy: 1,
            next_evolution: [12],
            prev_evolution: [10],
            location: ''
        },
        {
            id: 12,
            name: 'Butterfree',
            img: 'assets/images/pokemons/012.png',
            type: ['Bug', 'Flying'],
            candy: 'Caterpie Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Grass', 'Psychic', 'Dark', 'Fighting', 'Bug'],
            weaknesses:
            ['Fire',
                'Fighting',
                'Poison',
                'Flying',
                'Ghost',
                'Steel',
                'Fairy',
                'Electric',
                'Rock'],
            egg: 0,
            buddy: 1,
            next_evolution: [],
            prev_evolution: [10, 11],
            location: ''
        },
        {
            id: 13,
            name: 'Weedle',
            img: 'assets/images/pokemons/013.png',
            type: ['Bug', 'Poison'],
            candy: 'Weedle Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Grass', 'Psychic', 'Dark', 'Fairy'],
            weaknesses:
            ['Fire',
                'Fighting',
                'Poison',
                'Flying',
                'Ghost',
                'Steel',
                'Fairy',
                'Ground',
                'Rock'],
            egg: 2,
            buddy: 1,
            next_evolution: [14, 15],
            prev_evolution: [],
            location: ''
        },
        {
            id: 14,
            name: 'Kakuna',
            img: 'assets/images/pokemons/014.png',
            type: ['Bug', 'Poison'],
            candy: 'Weedle Candy',
            candy_count: '12',
            immunes: [],
            strengths: ['Grass', 'Psychic', 'Dark', 'Fairy'],
            weaknesses:
            ['Fire',
                'Fighting',
                'Poison',
                'Flying',
                'Ghost',
                'Steel',
                'Fairy',
                'Ground',
                'Rock'],
            egg: 0,
            buddy: 1,
            next_evolution: [15],
            prev_evolution: [13],
            location: ''
        },
        {
            id: 15,
            name: 'Beedrill',
            img: 'assets/images/pokemons/015.png',
            type: ['Bug', 'Poison'],
            candy: 'Weedle Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Grass', 'Psychic', 'Dark', 'Fairy'],
            weaknesses:
            ['Fire',
                'Fighting',
                'Poison',
                'Flying',
                'Ghost',
                'Steel',
                'Fairy',
                'Ground',
                'Rock'],
            egg: 0,
            buddy: 1,
            next_evolution: [],
            prev_evolution: [13, 14],
            location: ''
        },
        {
            id: 16,
            name: 'Pidgey',
            img: 'assets/images/pokemons/016.png',
            type: ['Normal', 'Flying'],
            candy: 'Pidgey Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Grass', 'Fighting', 'Bug'],
            weaknesses: ['Rock', 'Steel', 'Ghost', 'Electric'],
            egg: 2,
            buddy: 1,
            next_evolution: [17, 18],
            prev_evolution: [],
            location: ''
        },
        {
            id: 17,
            name: 'Pidgeotto',
            img: 'assets/images/pokemons/017.png',
            type: ['Normal', 'Flying'],
            candy: 'Pidgey Candy',
            candy_count: '12',
            immunes: [],
            strengths: ['Grass', 'Fighting', 'Bug'],
            weaknesses: ['Rock', 'Steel', 'Ghost', 'Electric'],
            egg: 0,
            buddy: 1,
            next_evolution: [18],
            prev_evolution: [16],
            location: ''
        },
        {
            id: 18,
            name: 'Pidgeot',
            img: 'assets/images/pokemons/018.png',
            type: ['Normal', 'Flying'],
            candy: 'Pidgey Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Grass', 'Fighting', 'Bug'],
            weaknesses: ['Rock', 'Steel', 'Ghost', 'Electric'],
            egg: 0,
            buddy: 1,
            next_evolution: [],
            prev_evolution: [16, 17],
            location: ''
        },
        {
            id: 19,
            name: 'Rattata',
            img: 'assets/images/pokemons/019.png',
            type: ['Normal'],
            candy: 'Rattata Candy',
            candy_count: 0,
            immunes: [],
            strengths: [],
            weaknesses: ['Rock', 'Steel', 'Ghost'],
            egg: 2,
            buddy: 1,
            next_evolution: [20],
            prev_evolution: [],
            location: ''
        },
        {
            id: 20,
            name: 'Raticate',
            img: 'assets/images/pokemons/020.png',
            type: ['Normal'],
            candy: 'Rattata Candy',
            candy_count: '25',
            immunes: [],
            strengths: [],
            weaknesses: ['Rock', 'Steel', 'Ghost'],
            egg: 0,
            buddy: 1,
            next_evolution: [],
            prev_evolution: [19],
            location: ''
        },
        {
            id: 21,
            name: 'Spearow',
            img: 'assets/images/pokemons/021.png',
            type: ['Normal', 'Flying'],
            candy: 'Spearow Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Grass', 'Fighting', 'Bug'],
            weaknesses: ['Rock', 'Steel', 'Ghost', 'Electric'],
            egg: 2,
            buddy: 1,
            next_evolution: [22],
            prev_evolution: [],
            location: ''
        },
        {
            id: 22,
            name: 'Fearow',
            img: 'assets/images/pokemons/022.png',
            type: ['Normal', 'Flying'],
            candy: 'Spearow Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Grass', 'Fighting', 'Bug'],
            weaknesses: ['Rock', 'Steel', 'Ghost', 'Electric'],
            egg: 0,
            buddy: 1,
            next_evolution: [],
            prev_evolution: [21],
            location: ''
        },
        {
            id: 23,
            name: 'Ekans',
            img: 'assets/images/pokemons/023.png',
            type: ['Poison'],
            candy: 'Ekans Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Grass', 'Fairy'],
            weaknesses: ['Poison', 'Ground', 'Rock', 'Ghost', 'Steel'],
            egg: 5,
            buddy: 3,
            next_evolution: [24],
            prev_evolution: [],
            location: ''
        },
        {
            id: 24,
            name: 'Arbok',
            img: 'assets/images/pokemons/024.png',
            type: ['Poison'],
            candy: 'Ekans Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Grass', 'Fairy'],
            weaknesses: ['Poison', 'Ground', 'Rock', 'Ghost', 'Steel'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [23],
            location: ''
        },
        {
            id: 25,
            name: 'Pikachu',
            img: 'assets/images/pokemons/025.png',
            type: ['Electric'],
            candy: 'Pikachu Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Water', 'Flying'],
            weaknesses: ['Electric', 'Grass', 'Dragon', 'Ground'],
            egg: 2,
            buddy: 1,
            next_evolution: [26],
            prev_evolution: [],
            location: ''
        },
        {
            id: 26,
            name: 'Raichu',
            img: 'assets/images/pokemons/026.png',
            type: ['Electric'],
            candy: 'Pikachu Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Water', 'Flying'],
            weaknesses: ['Electric', 'Grass', 'Dragon', 'Ground'],
            egg: 0,
            buddy: 1,
            next_evolution: [],
            prev_evolution: [25],
            location: ''
        },
        {
            id: 27,
            name: 'Sandshrew',
            img: 'assets/images/pokemons/027.png',
            type: ['Ground'],
            candy: 'Sandshrew Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Fire', 'Electric', 'Poison', 'Rock', 'Steel'],
            weaknesses: ['Grass', 'Bug', 'Flying'],
            egg: 5,
            buddy: 3,
            next_evolution: [28],
            prev_evolution: [],
            location: ''
        },
        {
            id: 28,
            name: 'Sandslash',
            img: 'assets/images/pokemons/028.png',
            type: ['Ground'],
            candy: 'Sandshrew Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Fire', 'Electric', 'Poison', 'Rock', 'Steel'],
            weaknesses: ['Grass', 'Bug', 'Flying'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [27],
            location: ''
        },
        {
            id: 29,
            name: 'Nidoran♀',
            img: 'assets/images/pokemons/029.png',
            type: ['Poison'],
            candy: 'Nidoran♀ Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Grass', 'Fairy'],
            weaknesses: ['Poison', 'Ground', 'Rock', 'Ghost', 'Steel'],
            egg: 5,
            buddy: 3,
            next_evolution: [30, 31],
            prev_evolution: [],
            location: ''
        },
        {
            id: 30,
            name: 'Nidorina',
            img: 'assets/images/pokemons/030.png',
            type: ['Poison'],
            candy: 'Nidoran♀ Candy',
            candy_count: '25',
            immunes: [],
            strengths: ['Grass', 'Fairy'],
            weaknesses: ['Poison', 'Ground', 'Rock', 'Ghost', 'Steel'],
            egg: 0,
            buddy: 3,
            next_evolution: [31],
            prev_evolution: [29],
            location: ''
        },
        {
            id: 31,
            name: 'Nidoqueen',
            img: 'assets/images/pokemons/031.png',
            type: ['Poison', 'Ground'],
            candy: 'Nidoran♀ Candy',
            candy_count: '100',
            immunes: [],
            strengths: ['Grass', 'Fairy', 'Fire', 'Electric', 'Poison', 'Rock', 'Steel'],
            weaknesses:
            ['Poison',
                'Ground',
                'Rock',
                'Ghost',
                'Steel',
                'Grass',
                'Bug',
                'Flying'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [29, 30],
            location: ''
        },
        {
            id: 32,
            name: 'Nidoran♂',
            img: 'assets/images/pokemons/032.png',
            type: ['Poison'],
            candy: 'Nidoran♂ Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Grass', 'Fairy'],
            weaknesses: ['Poison', 'Ground', 'Rock', 'Ghost', 'Steel'],
            egg: 5,
            buddy: 3,
            next_evolution: [33, 34],
            prev_evolution: [],
            location: ''
        },
        {
            id: 33,
            name: 'Nidorino',
            img: 'assets/images/pokemons/033.png',
            type: ['Poison'],
            candy: 'Nidoran♂ Candy',
            candy_count: '25',
            immunes: [],
            strengths: ['Grass', 'Fairy'],
            weaknesses: ['Poison', 'Ground', 'Rock', 'Ghost', 'Steel'],
            egg: 0,
            buddy: 3,
            next_evolution: [34],
            prev_evolution: [32],
            location: ''
        },
        {
            id: 34,
            name: 'Nidoking',
            img: 'assets/images/pokemons/034.png',
            type: ['Poison', 'Ground'],
            candy: 'Nidoran♂ Candy',
            candy_count: '100',
            immunes: [],
            strengths: ['Grass', 'Fairy', 'Fire', 'Electric', 'Poison', 'Rock', 'Steel'],
            weaknesses:
            ['Poison',
                'Ground',
                'Rock',
                'Ghost',
                'Steel',
                'Grass',
                'Bug',
                'Flying'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [32, 33],
            location: ''
        },
        {
            id: 35,
            name: 'Clefairy',
            img: 'assets/images/pokemons/035.png',
            type: ['Fairy'],
            candy: 'Clefairy Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Fighting', 'Dragon', 'Dark'],
            weaknesses: ['Fire', 'Poison', 'Steel'],
            egg: 2,
            buddy: 1,
            next_evolution: [36],
            prev_evolution: [],
            location: ''
        },
        {
            id: 36,
            name: 'Clefable',
            img: 'assets/images/pokemons/036.png',
            type: ['Fairy'],
            candy: 'Clefairy Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Fighting', 'Dragon', 'Dark'],
            weaknesses: ['Fire', 'Poison', 'Steel'],
            egg: 0,
            buddy: 1,
            next_evolution: [],
            prev_evolution: [35],
            location: ''
        },
        {
            id: 37,
            name: 'Vulpix',
            img: 'assets/images/pokemons/037.png',
            type: ['Fire'],
            candy: 'Vulpix Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Grass', 'Ice', 'Bug', 'Steel'],
            weaknesses: ['Fire', 'Water', 'Rock', 'Dragon'],
            egg: 5,
            buddy: 3,
            next_evolution: [38],
            prev_evolution: [],
            location: ''
        },
        {
            id: 38,
            name: 'Ninetales',
            img: 'assets/images/pokemons/038.png',
            type: ['Fire'],
            candy: 'Vulpix Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Grass', 'Ice', 'Bug', 'Steel'],
            weaknesses: ['Fire', 'Water', 'Rock', 'Dragon'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [37],
            location: ''
        },
        {
            id: 39,
            name: 'Jigglypuff',
            img: 'assets/images/pokemons/039.png',
            type: ['Normal'],
            candy: 'Jigglypuff Candy',
            candy_count: 0,
            immunes: [],
            strengths: [],
            weaknesses: ['Rock', 'Steel', 'Ghost'],
            egg: 2,
            buddy: 1,
            next_evolution: [40],
            prev_evolution: [],
            location: ''
        },
        {
            id: 40,
            name: 'Wigglytuff',
            img: 'assets/images/pokemons/040.png',
            type: ['Normal'],
            candy: 'Jigglypuff Candy',
            candy_count: '50',
            immunes: [],
            strengths: [],
            weaknesses: ['Rock', 'Steel', 'Ghost'],
            egg: 0,
            buddy: 1,
            next_evolution: [],
            prev_evolution: [39],
            location: ''
        },
        {
            id: 41,
            name: 'Zubat',
            img: 'assets/images/pokemons/041.png',
            type: ['Poison', 'Flying'],
            candy: 'Zubat Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Grass', 'Fairy', 'Fighting', 'Bug'],
            weaknesses: ['Poison', 'Ground', 'Rock', 'Ghost', 'Steel', 'Electric'],
            egg: 2,
            buddy: 1,
            next_evolution: [42],
            prev_evolution: [],
            location: ''
        },
        {
            id: 42,
            name: 'Golbat',
            img: 'assets/images/pokemons/042.png',
            type: ['Poison', 'Flying'],
            candy: 'Zubat Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Grass', 'Fairy', 'Fighting', 'Bug'],
            weaknesses: ['Poison', 'Ground', 'Rock', 'Ghost', 'Steel', 'Electric'],
            egg: 0,
            buddy: 1,
            next_evolution: [],
            prev_evolution: [41],
            location: ''
        },
        {
            id: 43,
            name: 'Oddish',
            img: 'assets/images/pokemons/043.png',
            type: ['Grass', 'Poison'],
            candy: 'Oddish Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Water', 'Ground', 'Rock', 'Grass', 'Fairy'],
            weaknesses:
            ['Fire',
                'Grass',
                'Poison',
                'Flying',
                'Bug',
                'Dragon',
                'Steel',
                'Ground',
                'Rock',
                'Ghost'],
            egg: 5,
            buddy: 3,
            next_evolution: [44, 45],
            prev_evolution: [],
            location: ''
        },
        {
            id: 44,
            name: 'Gloom',
            img: 'assets/images/pokemons/044.png',
            type: ['Grass', 'Poison'],
            candy: 'Oddish Candy',
            candy_count: '25',
            immunes: [],
            strengths: ['Water', 'Ground', 'Rock', 'Grass', 'Fairy'],
            weaknesses:
            ['Fire',
                'Grass',
                'Poison',
                'Flying',
                'Bug',
                'Dragon',
                'Steel',
                'Ground',
                'Rock',
                'Ghost'],
            egg: 0,
            buddy: 3,
            next_evolution: [45],
            prev_evolution: [43],
            location: ''
        },
        {
            id: 45,
            name: 'Vileplume',
            img: 'assets/images/pokemons/045.png',
            type: ['Grass', 'Poison'],
            candy: 'Oddish Candy',
            candy_count: '100',
            immunes: [],
            strengths: ['Water', 'Ground', 'Rock', 'Grass', 'Fairy'],
            weaknesses:
            ['Fire',
                'Grass',
                'Poison',
                'Flying',
                'Bug',
                'Dragon',
                'Steel',
                'Ground',
                'Rock',
                'Ghost'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [43, 44],
            location: ''
        },
        {
            id: 46,
            name: 'Paras',
            img: 'assets/images/pokemons/046.png',
            type: ['Bug', 'Grass'],
            candy: 'Paras Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Grass', 'Psychic', 'Dark', 'Water', 'Ground', 'Rock'],
            weaknesses:
            ['Fire',
                'Fighting',
                'Poison',
                'Flying',
                'Ghost',
                'Steel',
                'Fairy',
                'Grass',
                'Bug',
                'Dragon'],
            egg: 5,
            buddy: 3,
            next_evolution: [47],
            prev_evolution: [],
            location: ''
        },
        {
            id: 47,
            name: 'Parasect',
            img: 'assets/images/pokemons/047.png',
            type: ['Bug', 'Grass'],
            candy: 'Paras Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Grass', 'Psychic', 'Dark', 'Water', 'Ground', 'Rock'],
            weaknesses:
            ['Fire',
                'Fighting',
                'Poison',
                'Flying',
                'Ghost',
                'Steel',
                'Fairy',
                'Grass',
                'Bug',
                'Dragon'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [46],
            location: ''
        },
        {
            id: 48,
            name: 'Venonat',
            img: 'assets/images/pokemons/048.png',
            type: ['Bug', 'Poison'],
            candy: 'Venonat Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Grass', 'Psychic', 'Dark', 'Fairy'],
            weaknesses:
            ['Fire',
                'Fighting',
                'Poison',
                'Flying',
                'Ghost',
                'Steel',
                'Fairy',
                'Ground',
                'Rock'],
            egg: 5,
            buddy: 3,
            next_evolution: [49],
            prev_evolution: [],
            location: ''
        },
        {
            id: 49,
            name: 'Venomoth',
            img: 'assets/images/pokemons/049.png',
            type: ['Bug', 'Poison'],
            candy: 'Venonat Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Grass', 'Psychic', 'Dark', 'Fairy'],
            weaknesses:
            ['Fire',
                'Fighting',
                'Poison',
                'Flying',
                'Ghost',
                'Steel',
                'Fairy',
                'Ground',
                'Rock'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [48],
            location: ''
        },
        {
            id: 50,
            name: 'Diglett',
            img: 'assets/images/pokemons/050.png',
            type: ['Ground'],
            candy: 'Diglett Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Fire', 'Electric', 'Poison', 'Rock', 'Steel'],
            weaknesses: ['Grass', 'Bug', 'Flying'],
            egg: 5,
            buddy: 3,
            next_evolution: [51],
            prev_evolution: [],
            location: ''
        },
        {
            id: 51,
            name: 'Dugtrio',
            img: 'assets/images/pokemons/051.png',
            type: ['Ground'],
            candy: 'Diglett Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Fire', 'Electric', 'Poison', 'Rock', 'Steel'],
            weaknesses: ['Grass', 'Bug', 'Flying'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [50],
            location: ''
        },
        {
            id: 52,
            name: 'Meowth',
            img: 'assets/images/pokemons/052.png',
            type: ['Normal'],
            candy: 'Meowth Candy',
            candy_count: 0,
            immunes: [],
            strengths: [],
            weaknesses: ['Rock', 'Steel', 'Ghost'],
            egg: 5,
            buddy: 3,
            next_evolution: [53],
            prev_evolution: [],
            location: ''
        },
        {
            id: 53,
            name: 'Persian',
            img: 'assets/images/pokemons/053.png',
            type: ['Normal'],
            candy: 'Meowth Candy',
            candy_count: '50',
            immunes: [],
            strengths: [],
            weaknesses: ['Rock', 'Steel', 'Ghost'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [52],
            location: ''
        },
        {
            id: 54,
            name: 'Psyduck',
            img: 'assets/images/pokemons/054.png',
            type: ['Water'],
            candy: 'Psyduck Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock'],
            weaknesses: ['Water', 'Grass', 'Dragon'],
            egg: 5,
            buddy: 3,
            next_evolution: [55],
            prev_evolution: [],
            location: ''
        },
        {
            id: 55,
            name: 'Golduck',
            img: 'assets/images/pokemons/055.png',
            type: ['Water'],
            candy: 'Psyduck Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock'],
            weaknesses: ['Water', 'Grass', 'Dragon'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [54],
            location: ''
        },
        {
            id: 56,
            name: 'Mankey',
            img: 'assets/images/pokemons/056.png',
            type: ['Fighting'],
            candy: 'Mankey Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Normal', 'Ice', 'Rock', 'Dark', 'Steel'],
            weaknesses: ['Poison', 'Flying', 'Psychic', 'Bug', 'Fairy', 'Ghost'],
            egg: 5,
            buddy: 3,
            next_evolution: [57],
            prev_evolution: [],
            location: ''
        },
        {
            id: 57,
            name: 'Primeape',
            img: 'assets/images/pokemons/057.png',
            type: ['Fighting'],
            candy: 'Mankey Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Normal', 'Ice', 'Rock', 'Dark', 'Steel'],
            weaknesses: ['Poison', 'Flying', 'Psychic', 'Bug', 'Fairy', 'Ghost'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [56],
            location: ''
        },
        {
            id: 58,
            name: 'Growlithe',
            img: 'assets/images/pokemons/058.png',
            type: ['Fire'],
            candy: 'Growlithe Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Grass', 'Ice', 'Bug', 'Steel'],
            weaknesses: ['Fire', 'Water', 'Rock', 'Dragon'],
            egg: 5,
            buddy: 3,
            next_evolution: [59],
            prev_evolution: [],
            location: ''
        },
        {
            id: 59,
            name: 'Arcanine',
            img: 'assets/images/pokemons/059.png',
            type: ['Fire'],
            candy: 'Growlithe Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Grass', 'Ice', 'Bug', 'Steel'],
            weaknesses: ['Fire', 'Water', 'Rock', 'Dragon'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [58],
            location: ''
        },
        {
            id: 60,
            name: 'Poliwag',
            img: 'assets/images/pokemons/060.png',
            type: ['Water'],
            candy: 'Poliwag Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock'],
            weaknesses: ['Water', 'Grass', 'Dragon'],
            egg: 5,
            buddy: 3,
            next_evolution: [61, 62],
            prev_evolution: [],
            location: ''
        },
        {
            id: 61,
            name: 'Poliwhirl',
            img: 'assets/images/pokemons/061.png',
            type: ['Water'],
            candy: 'Poliwag Candy',
            candy_count: '25',
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock'],
            weaknesses: ['Water', 'Grass', 'Dragon'],
            egg: 0,
            buddy: 3,
            next_evolution: [62],
            prev_evolution: [60],
            location: ''
        },
        {
            id: 62,
            name: 'Poliwrath',
            img: 'assets/images/pokemons/062.png',
            type: ['Water', 'Fighting'],
            candy: 'Poliwag Candy',
            candy_count: '100',
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock', 'Normal', 'Ice', 'Dark', 'Steel'],
            weaknesses:
            ['Water',
                'Grass',
                'Dragon',
                'Poison',
                'Flying',
                'Psychic',
                'Bug',
                'Fairy',
                'Ghost'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [60, 61],
            location: ''
        },
        {
            id: 63,
            name: 'Abra',
            img: 'assets/images/pokemons/063.png',
            type: ['Psychic'],
            candy: 'Abra Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Fighting', 'Poison'],
            weaknesses: ['Psychic', 'Steel', 'Dark'],
            egg: 5,
            buddy: 3,
            next_evolution: [64, 65],
            prev_evolution: [],
            location: ''
        },
        {
            id: 64,
            name: 'Kadabra',
            img: 'assets/images/pokemons/064.png',
            type: ['Psychic'],
            candy: 'Abra Candy',
            candy_count: '25',
            immunes: [],
            strengths: ['Fighting', 'Poison'],
            weaknesses: ['Psychic', 'Steel', 'Dark'],
            egg: 0,
            buddy: 3,
            next_evolution: [65],
            prev_evolution: [63],
            location: ''
        },
        {
            id: 65,
            name: 'Alakazam',
            img: 'assets/images/pokemons/065.png',
            type: ['Psychic'],
            candy: 'Abra Candy',
            candy_count: '100',
            immunes: [],
            strengths: ['Fighting', 'Poison'],
            weaknesses: ['Psychic', 'Steel', 'Dark'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [63, 64],
            location: ''
        },
        {
            id: 66,
            name: 'Machop',
            img: 'assets/images/pokemons/066.png',
            type: ['Fighting'],
            candy: 'Machop Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Normal', 'Ice', 'Rock', 'Dark', 'Steel'],
            weaknesses: ['Poison', 'Flying', 'Psychic', 'Bug', 'Fairy', 'Ghost'],
            egg: 5,
            buddy: 3,
            next_evolution: [67, 68],
            prev_evolution: [],
            location: ''
        },
        {
            id: 67,
            name: 'Machoke',
            img: 'assets/images/pokemons/067.png',
            type: ['Fighting'],
            candy: 'Machop Candy',
            candy_count: '25',
            immunes: [],
            strengths: ['Normal', 'Ice', 'Rock', 'Dark', 'Steel'],
            weaknesses: ['Poison', 'Flying', 'Psychic', 'Bug', 'Fairy', 'Ghost'],
            egg: 0,
            buddy: 3,
            next_evolution: [68],
            prev_evolution: [66],
            location: ''
        },
        {
            id: 68,
            name: 'Machamp',
            img: 'assets/images/pokemons/068.png',
            type: ['Fighting'],
            candy: 'Machop Candy',
            candy_count: '100',
            immunes: [],
            strengths: ['Normal', 'Ice', 'Rock', 'Dark', 'Steel'],
            weaknesses: ['Poison', 'Flying', 'Psychic', 'Bug', 'Fairy', 'Ghost'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [66, 67],
            location: ''
        },
        {
            id: 69,
            name: 'Bellsprout',
            img: 'assets/images/pokemons/069.png',
            type: ['Grass', 'Poison'],
            candy: 'Bellsprout Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Water', 'Ground', 'Rock', 'Grass', 'Fairy'],
            weaknesses:
            ['Fire',
                'Grass',
                'Poison',
                'Flying',
                'Bug',
                'Dragon',
                'Steel',
                'Ground',
                'Rock',
                'Ghost'],
            egg: 5,
            buddy: 3,
            next_evolution: [70, 71],
            prev_evolution: [],
            location: ''
        },
        {
            id: 70,
            name: 'Weepinbell',
            img: 'assets/images/pokemons/070.png',
            type: ['Grass', 'Poison'],
            candy: 'Bellsprout Candy',
            candy_count: '25',
            immunes: [],
            strengths: ['Water', 'Ground', 'Rock', 'Grass', 'Fairy'],
            weaknesses:
            ['Fire',
                'Grass',
                'Poison',
                'Flying',
                'Bug',
                'Dragon',
                'Steel',
                'Ground',
                'Rock',
                'Ghost'],
            egg: 0,
            buddy: 3,
            next_evolution: [71],
            prev_evolution: [69],
            location: ''
        },
        {
            id: 71,
            name: 'Victreebel',
            img: 'assets/images/pokemons/071.png',
            type: ['Grass', 'Poison'],
            candy: 'Bellsprout Candy',
            candy_count: '100',
            immunes: [],
            strengths: ['Water', 'Ground', 'Rock', 'Grass', 'Fairy'],
            weaknesses:
            ['Fire',
                'Grass',
                'Poison',
                'Flying',
                'Bug',
                'Dragon',
                'Steel',
                'Ground',
                'Rock',
                'Ghost'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [69, 70],
            location: ''
        },
        {
            id: 72,
            name: 'Tentacool',
            img: 'assets/images/pokemons/072.png',
            type: ['Water', 'Poison'],
            candy: 'Tentacool Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock', 'Grass', 'Fairy'],
            weaknesses:
            ['Water',
                'Grass',
                'Dragon',
                'Poison',
                'Ground',
                'Rock',
                'Ghost',
                'Steel'],
            egg: 5,
            buddy: 3,
            next_evolution: [73],
            prev_evolution: [],
            location: ''
        },
        {
            id: 73,
            name: 'Tentacruel',
            img: 'assets/images/pokemons/073.png',
            type: ['Water', 'Poison'],
            candy: 'Tentacool Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock', 'Grass', 'Fairy'],
            weaknesses:
            ['Water',
                'Grass',
                'Dragon',
                'Poison',
                'Ground',
                'Rock',
                'Ghost',
                'Steel'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [72],
            location: ''
        },
        {
            id: 74,
            name: 'Geodude',
            img: 'assets/images/pokemons/074.png',
            type: ['Rock', 'Ground'],
            candy: 'Geodude Candy',
            candy_count: 0,
            immunes: [],
            strengths:
            ['Fire',
                'Ice',
                'Flying',
                'Bug',
                'Electric',
                'Poison',
                'Rock',
                'Steel'],
            weaknesses: ['Fighting', 'Ground', 'Steel', 'Grass', 'Bug', 'Flying'],
            egg: 2,
            buddy: 1,
            next_evolution: [75, 76],
            prev_evolution: [],
            location: ''
        },
        {
            id: 75,
            name: 'Graveler',
            img: 'assets/images/pokemons/075.png',
            type: ['Rock', 'Ground'],
            candy: 'Geodude Candy',
            candy_count: '25',
            immunes: [],
            strengths:
            ['Fire',
                'Ice',
                'Flying',
                'Bug',
                'Electric',
                'Poison',
                'Rock',
                'Steel'],
            weaknesses: ['Fighting', 'Ground', 'Steel', 'Grass', 'Bug', 'Flying'],
            egg: 0,
            buddy: 1,
            next_evolution: [76],
            prev_evolution: [74],
            location: ''
        },
        {
            id: 76,
            name: 'Golem',
            img: 'assets/images/pokemons/076.png',
            type: ['Rock', 'Ground'],
            candy: 'Geodude Candy',
            candy_count: '100',
            immunes: [],
            strengths:
            ['Fire',
                'Ice',
                'Flying',
                'Bug',
                'Electric',
                'Poison',
                'Rock',
                'Steel'],
            weaknesses: ['Fighting', 'Ground', 'Steel', 'Grass', 'Bug', 'Flying'],
            egg: 0,
            buddy: 1,
            next_evolution: [],
            prev_evolution: [74, 75],
            location: ''
        },
        {
            id: 77,
            name: 'Ponyta',
            img: 'assets/images/pokemons/077.png',
            type: ['Fire'],
            candy: 'Ponyta Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Grass', 'Ice', 'Bug', 'Steel'],
            weaknesses: ['Fire', 'Water', 'Rock', 'Dragon'],
            egg: 5,
            buddy: 3,
            next_evolution: [78],
            prev_evolution: [],
            location: ''
        },
        {
            id: 78,
            name: 'Rapidash',
            img: 'assets/images/pokemons/078.png',
            type: ['Fire'],
            candy: 'Ponyta Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Grass', 'Ice', 'Bug', 'Steel'],
            weaknesses: ['Fire', 'Water', 'Rock', 'Dragon'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [77],
            location: ''
        },
        {
            id: 79,
            name: 'Slowpoke',
            img: 'assets/images/pokemons/079.png',
            type: ['Water', 'Psychic'],
            candy: 'Slowpoke Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock', 'Fighting', 'Poison'],
            weaknesses: ['Water', 'Grass', 'Dragon', 'Psychic', 'Steel', 'Dark'],
            egg: 5,
            buddy: 3,
            next_evolution: [80],
            prev_evolution: [],
            location: ''
        },
        {
            id: 80,
            name: 'Slowbro',
            img: 'assets/images/pokemons/080.png',
            type: ['Water', 'Psychic'],
            candy: 'Slowpoke Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock', 'Fighting', 'Poison'],
            weaknesses: ['Water', 'Grass', 'Dragon', 'Psychic', 'Steel', 'Dark'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [79],
            location: ''
        },
        {
            id: 81,
            name: 'Magnemite',
            img: 'assets/images/pokemons/081.png',
            type: ['Electric'],
            candy: 'Magnemite Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Water', 'Flying'],
            weaknesses: ['Electric', 'Grass', 'Dragon', 'Ground'],
            egg: 5,
            buddy: 3,
            next_evolution: [82],
            prev_evolution: [],
            location: ''
        },
        {
            id: 82,
            name: 'Magneton',
            img: 'assets/images/pokemons/082.png',
            type: ['Electric'],
            candy: 'Magnemite Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Water', 'Flying'],
            weaknesses: ['Electric', 'Grass', 'Dragon', 'Ground'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [81],
            location: ''
        },
        {
            id: 83,
            name: 'Farfetch\'d',
            img: 'assets/images/pokemons/083.png',
            type: ['Normal', 'Flying'],
            candy: 'Farfetch\'d Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Grass', 'Fighting', 'Bug'],
            weaknesses: ['Rock', 'Steel', 'Ghost', 'Electric'],
            egg: 5,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [],
            location: 'Asia'
        },
        {
            id: 84,
            name: 'Doduo',
            img: 'assets/images/pokemons/084.png',
            type: ['Normal', 'Flying'],
            candy: 'Doduo Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Grass', 'Fighting', 'Bug'],
            weaknesses: ['Rock', 'Steel', 'Ghost', 'Electric'],
            egg: 5,
            buddy: 3,
            next_evolution: [85],
            prev_evolution: [],
            location: ''
        },
        {
            id: 85,
            name: 'Dodrio',
            img: 'assets/images/pokemons/085.png',
            type: ['Normal', 'Flying'],
            candy: 'Doduo Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Grass', 'Fighting', 'Bug'],
            weaknesses: ['Rock', 'Steel', 'Ghost', 'Electric'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [84],
            location: ''
        },
        {
            id: 86,
            name: 'Seel',
            img: 'assets/images/pokemons/086.png',
            type: ['Water'],
            candy: 'Seel Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock'],
            weaknesses: ['Water', 'Grass', 'Dragon'],
            egg: 5,
            buddy: 3,
            next_evolution: [87],
            prev_evolution: [],
            location: ''
        },
        {
            id: 87,
            name: 'Dewgong',
            img: 'assets/images/pokemons/087.png',
            type: ['Water', 'Ice'],
            candy: 'Seel Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock', 'Grass', 'Flying', 'Dragon'],
            weaknesses: ['Water', 'Grass', 'Dragon', 'Fire', 'Ice', 'Steel'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [86],
            location: ''
        },
        {
            id: 88,
            name: 'Grimer',
            img: 'assets/images/pokemons/088.png',
            type: ['Poison'],
            candy: 'Grimer Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Grass', 'Fairy'],
            weaknesses: ['Poison', 'Ground', 'Rock', 'Ghost', 'Steel'],
            egg: 5,
            buddy: 3,
            next_evolution: [89],
            prev_evolution: [],
            location: ''
        },
        {
            id: 89,
            name: 'Muk',
            img: 'assets/images/pokemons/089.png',
            type: ['Poison'],
            candy: 'Grimer Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Grass', 'Fairy'],
            weaknesses: ['Poison', 'Ground', 'Rock', 'Ghost', 'Steel'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [88],
            location: ''
        },
        {
            id: 90,
            name: 'Shellder',
            img: 'assets/images/pokemons/090.png',
            type: ['Water'],
            candy: 'Shellder Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock'],
            weaknesses: ['Water', 'Grass', 'Dragon'],
            egg: 5,
            buddy: 3,
            next_evolution: [91],
            prev_evolution: [],
            location: ''
        },
        {
            id: 91,
            name: 'Cloyster',
            img: 'assets/images/pokemons/091.png',
            type: ['Water', 'Ice'],
            candy: 'Shellder Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock', 'Grass', 'Flying', 'Dragon'],
            weaknesses: ['Water', 'Grass', 'Dragon', 'Fire', 'Ice', 'Steel'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [90],
            location: ''
        },
        {
            id: 92,
            name: 'Gastly',
            img: 'assets/images/pokemons/092.png',
            type: ['Ghost', 'Poison'],
            candy: 'Gastly Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Psychic', 'Ghost', 'Grass', 'Fairy'],
            weaknesses: ['Dark', 'Normal', 'Poison', 'Ground', 'Rock', 'Ghost', 'Steel'],
            egg: 5,
            buddy: 3,
            next_evolution: [93, 94],
            prev_evolution: [],
            location: ''
        },
        {
            id: 93,
            name: 'Haunter',
            img: 'assets/images/pokemons/093.png',
            type: ['Ghost', 'Poison'],
            candy: 'Gastly Candy',
            candy_count: '25',
            immunes: [],
            strengths: ['Psychic', 'Ghost', 'Grass', 'Fairy'],
            weaknesses: ['Dark', 'Normal', 'Poison', 'Ground', 'Rock', 'Ghost', 'Steel'],
            egg: 0,
            buddy: 3,
            next_evolution: [94],
            prev_evolution: [92],
            location: ''
        },
        {
            id: 94,
            name: 'Gengar',
            img: 'assets/images/pokemons/094.png',
            type: ['Ghost', 'Poison'],
            candy: 'Gastly Candy',
            candy_count: '100',
            immunes: [],
            strengths: ['Psychic', 'Ghost', 'Grass', 'Fairy'],
            weaknesses: ['Dark', 'Normal', 'Poison', 'Ground', 'Rock', 'Ghost', 'Steel'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [92, 93],
            location: ''
        },
        {
            id: 95,
            name: 'Onix',
            img: 'assets/images/pokemons/095.png',
            type: ['Rock', 'Ground'],
            candy: 'Onix Candy',
            candy_count: 0,
            immunes: [],
            strengths:
            ['Fire',
                'Ice',
                'Flying',
                'Bug',
                'Electric',
                'Poison',
                'Rock',
                'Steel'],
            weaknesses: ['Fighting', 'Ground', 'Steel', 'Grass', 'Bug', 'Flying'],
            egg: 10,
            buddy: 5,
            next_evolution: [],
            prev_evolution: [],
            location: ''
        },
        {
            id: 96,
            name: 'Drowzee',
            img: 'assets/images/pokemons/096.png',
            type: ['Psychic'],
            candy: 'Drowzee Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Fighting', 'Poison'],
            weaknesses: ['Psychic', 'Steel', 'Dark'],
            egg: 5,
            buddy: 3,
            next_evolution: [97],
            prev_evolution: [],
            location: ''
        },
        {
            id: 97,
            name: 'Hypno',
            img: 'assets/images/pokemons/097.png',
            type: ['Psychic'],
            candy: 'Drowzee Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Fighting', 'Poison'],
            weaknesses: ['Psychic', 'Steel', 'Dark'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [96],
            location: ''
        },
        {
            id: 98,
            name: 'Krabby',
            img: 'assets/images/pokemons/098.png',
            type: ['Water'],
            candy: 'Krabby Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock'],
            weaknesses: ['Water', 'Grass', 'Dragon'],
            egg: 5,
            buddy: 3,
            next_evolution: [99],
            prev_evolution: [],
            location: ''
        },
        {
            id: 99,
            name: 'Kingler',
            img: 'assets/images/pokemons/099.png',
            type: ['Water'],
            candy: 'Krabby Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock'],
            weaknesses: ['Water', 'Grass', 'Dragon'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [98],
            location: ''
        },
        {
            id: 100,
            name: 'Voltorb',
            img: 'assets/images/pokemons/100.png',
            type: ['Electric'],
            candy: 'Voltorb Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Water', 'Flying'],
            weaknesses: ['Electric', 'Grass', 'Dragon', 'Ground'],
            egg: 5,
            buddy: 3,
            next_evolution: [101],
            prev_evolution: [],
            location: ''
        },
        {
            id: 101,
            name: 'Electrode',
            img: 'assets/images/pokemons/101.png',
            type: ['Electric'],
            candy: 'Voltorb Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Water', 'Flying'],
            weaknesses: ['Electric', 'Grass', 'Dragon', 'Ground'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [100],
            location: ''
        },
        {
            id: 102,
            name: 'Exeggcute',
            img: 'assets/images/pokemons/102.png',
            type: ['Grass', 'Psychic'],
            candy: 'Exeggcute Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Water', 'Ground', 'Rock', 'Fighting', 'Poison'],
            weaknesses:
            ['Fire',
                'Grass',
                'Poison',
                'Flying',
                'Bug',
                'Dragon',
                'Steel',
                'Psychic',
                'Dark'],
            egg: 5,
            buddy: 3,
            next_evolution: [103],
            prev_evolution: [],
            location: ''
        },
        {
            id: 103,
            name: 'Exeggutor',
            img: 'assets/images/pokemons/103.png',
            type: ['Grass', 'Psychic'],
            candy: 'Exeggcute Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Water', 'Ground', 'Rock', 'Fighting', 'Poison'],
            weaknesses:
            ['Fire',
                'Grass',
                'Poison',
                'Flying',
                'Bug',
                'Dragon',
                'Steel',
                'Psychic',
                'Dark'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [102],
            location: ''
        },
        {
            id: 104,
            name: 'Cubone',
            img: 'assets/images/pokemons/104.png',
            type: ['Ground'],
            candy: 'Cubone Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Fire', 'Electric', 'Poison', 'Rock', 'Steel'],
            weaknesses: ['Grass', 'Bug', 'Flying'],
            egg: 5,
            buddy: 3,
            next_evolution: [105],
            prev_evolution: [],
            location: ''
        },
        {
            id: 105,
            name: 'Marowak',
            img: 'assets/images/pokemons/105.png',
            type: ['Ground'],
            candy: 'Cubone Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Fire', 'Electric', 'Poison', 'Rock', 'Steel'],
            weaknesses: ['Grass', 'Bug', 'Flying'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [104],
            location: ''
        },
        {
            id: 106,
            name: 'Hitmonlee',
            img: 'assets/images/pokemons/106.png',
            type: ['Fighting'],
            candy: 'Hitmonlee Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Normal', 'Ice', 'Rock', 'Dark', 'Steel'],
            weaknesses: ['Poison', 'Flying', 'Psychic', 'Bug', 'Fairy', 'Ghost'],
            egg: 10,
            buddy: 5,
            next_evolution: [],
            prev_evolution: [],
            location: ''
        },
        {
            id: 107,
            name: 'Hitmonchan',
            img: 'assets/images/pokemons/107.png',
            type: ['Fighting'],
            candy: 'Hitmonchan Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Normal', 'Ice', 'Rock', 'Dark', 'Steel'],
            weaknesses: ['Poison', 'Flying', 'Psychic', 'Bug', 'Fairy', 'Ghost'],
            egg: 10,
            buddy: 5,
            next_evolution: [],
            prev_evolution: [],
            location: ''
        },
        {
            id: 108,
            name: 'Lickitung',
            img: 'assets/images/pokemons/108.png',
            type: ['Normal'],
            candy: 'Lickitung Candy',
            candy_count: 0,
            immunes: [],
            strengths: [],
            weaknesses: ['Rock', 'Steel', 'Ghost'],
            egg: 5,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [],
            location: ''
        },
        {
            id: 109,
            name: 'Koffing',
            img: 'assets/images/pokemons/109.png',
            type: ['Poison'],
            candy: 'Koffing Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Grass', 'Fairy'],
            weaknesses: ['Poison', 'Ground', 'Rock', 'Ghost', 'Steel'],
            egg: 5,
            buddy: 3,
            next_evolution: [110],
            prev_evolution: [],
            location: ''
        },
        {
            id: 110,
            name: 'Weezing',
            img: 'assets/images/pokemons/110.png',
            type: ['Poison'],
            candy: 'Koffing Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Grass', 'Fairy'],
            weaknesses: ['Poison', 'Ground', 'Rock', 'Ghost', 'Steel'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [109],
            location: ''
        },
        {
            id: 111,
            name: 'Rhyhorn',
            img: 'assets/images/pokemons/111.png',
            type: ['Ground', 'Rock'],
            candy: 'Rhyhorn Candy',
            candy_count: 0,
            immunes: [],
            strengths:
            ['Fire',
                'Electric',
                'Poison',
                'Rock',
                'Steel',
                'Ice',
                'Flying',
                'Bug'],
            weaknesses: ['Grass', 'Bug', 'Flying', 'Fighting', 'Ground', 'Steel'],
            egg: 5,
            buddy: 3,
            next_evolution: [112],
            prev_evolution: [],
            location: ''
        },
        {
            id: 112,
            name: 'Rhydon',
            img: 'assets/images/pokemons/112.png',
            type: ['Ground', 'Rock'],
            candy: 'Rhyhorn Candy',
            candy_count: '50',
            immunes: [],
            strengths:
            ['Fire',
                'Electric',
                'Poison',
                'Rock',
                'Steel',
                'Ice',
                'Flying',
                'Bug'],
            weaknesses: ['Grass', 'Bug', 'Flying', 'Fighting', 'Ground', 'Steel'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [111],
            location: ''
        },
        {
            id: 113,
            name: 'Chansey',
            img: 'assets/images/pokemons/113.png',
            type: ['Normal'],
            candy: 'Chansey Candy',
            candy_count: 0,
            immunes: [],
            strengths: [],
            weaknesses: ['Rock', 'Steel', 'Ghost'],
            egg: 10,
            buddy: 5,
            next_evolution: [],
            prev_evolution: [],
            location: ''
        },
        {
            id: 114,
            name: 'Tangela',
            img: 'assets/images/pokemons/114.png',
            type: ['Grass'],
            candy: 'Tangela Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Water', 'Ground', 'Rock'],
            weaknesses: ['Fire', 'Grass', 'Poison', 'Flying', 'Bug', 'Dragon', 'Steel'],
            egg: 5,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [],
            location: ''
        },
        {
            id: 115,
            name: 'Kangaskhan',
            img: 'assets/images/pokemons/115.png',
            type: ['Normal'],
            candy: 'Kangaskhan Candy',
            candy_count: 0,
            immunes: [],
            strengths: [],
            weaknesses: ['Rock', 'Steel', 'Ghost'],
            egg: 5,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [],
            location: 'Australia'
        },
        {
            id: 116,
            name: 'Horsea',
            img: 'assets/images/pokemons/116.png',
            type: ['Water'],
            candy: 'Horsea Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock'],
            weaknesses: ['Water', 'Grass', 'Dragon'],
            egg: 5,
            buddy: 3,
            next_evolution: [117],
            prev_evolution: [],
            location: ''
        },
        {
            id: 117,
            name: 'Seadra',
            img: 'assets/images/pokemons/117.png',
            type: ['Water'],
            candy: 'Horsea Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock'],
            weaknesses: ['Water', 'Grass', 'Dragon'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [116],
            location: ''
        },
        {
            id: 118,
            name: 'Goldeen',
            img: 'assets/images/pokemons/118.png',
            type: ['Water'],
            candy: 'Goldeen Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock'],
            weaknesses: ['Water', 'Grass', 'Dragon'],
            egg: 5,
            buddy: 3,
            next_evolution: [119],
            prev_evolution: [],
            location: ''
        },
        {
            id: 119,
            name: 'Seaking',
            img: 'assets/images/pokemons/119.png',
            type: ['Water'],
            candy: 'Goldeen Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock'],
            weaknesses: ['Water', 'Grass', 'Dragon'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [118],
            location: ''
        },
        {
            id: 120,
            name: 'Staryu',
            img: 'assets/images/pokemons/120.png',
            type: ['Water'],
            candy: 'Staryu Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock'],
            weaknesses: ['Water', 'Grass', 'Dragon'],
            egg: 5,
            buddy: 3,
            next_evolution: [121],
            prev_evolution: [],
            location: ''
        },
        {
            id: 121,
            name: 'Starmie',
            img: 'assets/images/pokemons/121.png',
            type: ['Water', 'Psychic'],
            candy: 'Staryu Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock', 'Fighting', 'Poison'],
            weaknesses: ['Water', 'Grass', 'Dragon', 'Psychic', 'Steel', 'Dark'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [120],
            location: ''
        },
        {
            id: 122,
            name: 'Mr. Mime',
            img: 'assets/images/pokemons/122.png',
            type: ['Psychic'],
            candy: 'Mr. Mime Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Fighting', 'Poison'],
            weaknesses: ['Psychic', 'Steel', 'Dark'],
            egg: 10,
            buddy: 5,
            next_evolution: [],
            prev_evolution: [],
            location: 'Europe'
        },
        {
            id: 123,
            name: 'Scyther',
            img: 'assets/images/pokemons/123.png',
            type: ['Bug', 'Flying'],
            candy: 'Scyther Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Grass', 'Psychic', 'Dark', 'Fighting', 'Bug'],
            weaknesses:
            ['Fire',
                'Fighting',
                'Poison',
                'Flying',
                'Ghost',
                'Steel',
                'Fairy',
                'Electric',
                'Rock'],
            egg: 10,
            buddy: 5,
            next_evolution: [],
            prev_evolution: [],
            location: ''
        },
        {
            id: 124,
            name: 'Jynx',
            img: 'assets/images/pokemons/124.png',
            type: ['Ice', 'Psychic'],
            candy: 'Jynx Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Grass', 'Ground', 'Flying', 'Dragon', 'Fighting', 'Poison'],
            weaknesses: ['Fire', 'Water', 'Ice', 'Steel', 'Psychic', 'Dark'],
            egg: 10,
            buddy: 5,
            next_evolution: [],
            prev_evolution: [],
            location: ''
        },
        {
            id: 125,
            name: 'Electabuzz',
            img: 'assets/images/pokemons/125.png',
            type: ['Electric'],
            candy: 'Electabuzz Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Water', 'Flying'],
            weaknesses: ['Electric', 'Grass', 'Dragon', 'Ground'],
            egg: 10,
            buddy: 5,
            next_evolution: [],
            prev_evolution: [],
            location: ''
        },
        {
            id: 126,
            name: 'Magmar',
            img: 'assets/images/pokemons/126.png',
            type: ['Fire'],
            candy: 'Magmar Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Grass', 'Ice', 'Bug', 'Steel'],
            weaknesses: ['Fire', 'Water', 'Rock', 'Dragon'],
            egg: 10,
            buddy: 5,
            next_evolution: [],
            prev_evolution: [],
            location: ''
        },
        {
            id: 127,
            name: 'Pinsir',
            img: 'assets/images/pokemons/127.png',
            type: ['Bug'],
            candy: 'Pinsir Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Grass', 'Psychic', 'Dark'],
            weaknesses: ['Fire', 'Fighting', 'Poison', 'Flying', 'Ghost', 'Steel', 'Fairy'],
            egg: 10,
            buddy: 5,
            next_evolution: [],
            prev_evolution: [],
            location: ''
        },
        {
            id: 128,
            name: 'Tauros',
            img: 'assets/images/pokemons/128.png',
            type: ['Normal'],
            candy: 'Tauros Candy',
            candy_count: 0,
            immunes: [],
            strengths: [],
            weaknesses: ['Rock', 'Steel', 'Ghost'],
            egg: 5,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [],
            location: 'North America'
        },
        {
            id: 129,
            name: 'Magikarp',
            img: 'assets/images/pokemons/129.png',
            type: ['Water'],
            candy: 'Magikarp Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock'],
            weaknesses: ['Water', 'Grass', 'Dragon'],
            egg: 2,
            buddy: 1,
            next_evolution: [130],
            prev_evolution: [],
            location: ''
        },
        {
            id: 130,
            name: 'Gyarados',
            img: 'assets/images/pokemons/130.png',
            type: ['Water', 'Flying'],
            candy: 'Magikarp Candy',
            candy_count: '400',
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock', 'Grass', 'Fighting', 'Bug'],
            weaknesses: ['Water', 'Grass', 'Dragon', 'Electric', 'Rock', 'Steel'],
            egg: 0,
            buddy: 1,
            next_evolution: [],
            prev_evolution: [129],
            location: ''
        },
        {
            id: 131,
            name: 'Lapras',
            img: 'assets/images/pokemons/131.png',
            type: ['Water', 'Ice'],
            candy: 'Lapras Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock', 'Grass', 'Flying', 'Dragon'],
            weaknesses: ['Water', 'Grass', 'Dragon', 'Fire', 'Ice', 'Steel'],
            egg: 10,
            buddy: 5,
            next_evolution: [],
            prev_evolution: [],
            location: ''
        },
        {
            id: 132,
            name: 'Ditto',
            img: 'assets/images/pokemons/132.png',
            type: ['Normal'],
            candy: 'None',
            candy_count: 0,
            immunes: [],
            strengths: [],
            weaknesses: ['Rock', 'Steel', 'Ghost'],
            egg: 0,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [],
            location: 'Unavailable'
        },
        {
            id: 133,
            name: 'Eevee',
            img: 'assets/images/pokemons/133.png',
            type: ['Normal'],
            candy: 'Eevee Candy',
            candy_count: 0,
            immunes: [],
            strengths: [],
            weaknesses: ['Rock', 'Steel', 'Ghost'],
            egg: 10,
            buddy: 5,
            next_evolution: [134, 135, 136],
            prev_evolution: [],
            location: ''
        },
        {
            id: 134,
            name: 'Vaporeon',
            img: 'assets/images/pokemons/134.png',
            type: ['Water'],
            candy: 'Eevee Candy',
            candy_count: '25',
            immunes: [],
            strengths: ['Fire', 'Ground', 'Rock'],
            weaknesses: ['Water', 'Grass', 'Dragon'],
            egg: 0,
            buddy: 5,
            next_evolution: [],
            prev_evolution: [133],
            location: ''
        },
        {
            id: 135,
            name: 'Jolteon',
            img: 'assets/images/pokemons/135.png',
            type: ['Electric'],
            candy: 'Eevee Candy',
            candy_count: '25',
            immunes: [],
            strengths: ['Water', 'Flying'],
            weaknesses: ['Electric', 'Grass', 'Dragon', 'Ground'],
            egg: 0,
            buddy: 5,
            next_evolution: [],
            prev_evolution: [133],
            location: ''
        },
        {
            id: 136,
            name: 'Flareon',
            img: 'assets/images/pokemons/136.png',
            type: ['Fire'],
            candy: 'Eevee Candy',
            candy_count: '25',
            immunes: [],
            strengths: ['Grass', 'Ice', 'Bug', 'Steel'],
            weaknesses: ['Fire', 'Water', 'Rock', 'Dragon'],
            egg: 0,
            buddy: 5,
            next_evolution: [],
            prev_evolution: [133],
            location: ''
        },
        {
            id: 137,
            name: 'Porygon',
            img: 'assets/images/pokemons/137.png',
            type: ['Normal'],
            candy: 'Porygon Candy',
            candy_count: 0,
            immunes: [],
            strengths: [],
            weaknesses: ['Rock', 'Steel', 'Ghost'],
            egg: 5,
            buddy: 3,
            next_evolution: [],
            prev_evolution: [],
            location: ''
        },
        {
            id: 138,
            name: 'Omanyte',
            img: 'assets/images/pokemons/138.png',
            type: ['Rock', 'Water'],
            candy: 'Omanyte Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Fire', 'Ice', 'Flying', 'Bug', 'Ground', 'Rock'],
            weaknesses: ['Fighting', 'Ground', 'Steel', 'Water', 'Grass', 'Dragon'],
            egg: 10,
            buddy: 5,
            next_evolution: [139],
            prev_evolution: [],
            location: ''
        },
        {
            id: 139,
            name: 'Omastar',
            img: 'assets/images/pokemons/139.png',
            type: ['Rock', 'Water'],
            candy: 'Omanyte Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Fire', 'Ice', 'Flying', 'Bug', 'Ground', 'Rock'],
            weaknesses: ['Fighting', 'Ground', 'Steel', 'Water', 'Grass', 'Dragon'],
            egg: 0,
            buddy: 5,
            next_evolution: [],
            prev_evolution: [138],
            location: ''
        },
        {
            id: 140,
            name: 'Kabuto',
            img: 'assets/images/pokemons/140.png',
            type: ['Rock', 'Water'],
            candy: 'Kabuto Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Fire', 'Ice', 'Flying', 'Bug', 'Ground', 'Rock'],
            weaknesses: ['Fighting', 'Ground', 'Steel', 'Water', 'Grass', 'Dragon'],
            egg: 10,
            buddy: 5,
            next_evolution: [141],
            prev_evolution: [],
            location: ''
        },
        {
            id: 141,
            name: 'Kabutops',
            img: 'assets/images/pokemons/141.png',
            type: ['Rock', 'Water'],
            candy: 'Kabuto Candy',
            candy_count: '50',
            immunes: [],
            strengths: ['Fire', 'Ice', 'Flying', 'Bug', 'Ground', 'Rock'],
            weaknesses: ['Fighting', 'Ground', 'Steel', 'Water', 'Grass', 'Dragon'],
            egg: 0,
            buddy: 5,
            next_evolution: [],
            prev_evolution: [140],
            location: ''
        },
        {
            id: 142,
            name: 'Aerodactyl',
            img: 'assets/images/pokemons/142.png',
            type: ['Rock', 'Flying'],
            candy: 'Aerodactyl Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Fire', 'Ice', 'Flying', 'Bug', 'Grass', 'Fighting'],
            weaknesses: ['Fighting', 'Ground', 'Steel', 'Electric', 'Rock'],
            egg: 10,
            buddy: 5,
            next_evolution: [],
            prev_evolution: [],
            location: ''
        },
        {
            id: 143,
            name: 'Snorlax',
            img: 'assets/images/pokemons/143.png',
            type: ['Normal'],
            candy: 'Snorlax Candy',
            candy_count: 0,
            immunes: [],
            strengths: [],
            weaknesses: ['Rock', 'Steel', 'Ghost'],
            egg: 10,
            buddy: 5,
            next_evolution: [],
            prev_evolution: [],
            location: ''
        },
        {
            id: 144,
            name: 'Articuno',
            img: 'assets/images/pokemons/144.png',
            type: ['Ice', 'Flying'],
            candy: 'None',
            candy_count: 0,
            immunes: [],
            strengths: ['Grass', 'Ground', 'Flying', 'Dragon', 'Fighting', 'Bug'],
            weaknesses: ['Fire', 'Water', 'Ice', 'Steel', 'Electric', 'Rock'],
            egg: 0,
            buddy: 5,
            next_evolution: [],
            prev_evolution: [],
            location: 'Unavailable'
        },
        {
            id: 145,
            name: 'Zapdos',
            img: 'assets/images/pokemons/145.png',
            type: ['Electric', 'Flying'],
            candy: 'None',
            candy_count: 0,
            immunes: [],
            strengths: ['Water', 'Flying', 'Grass', 'Fighting', 'Bug'],
            weaknesses: ['Electric', 'Grass', 'Dragon', 'Ground', 'Rock', 'Steel'],
            egg: 0,
            buddy: 5,
            next_evolution: [],
            prev_evolution: [],
            location: 'Unavailable'
        },
        {
            id: 146,
            name: 'Moltres',
            img: 'assets/images/pokemons/146.png',
            type: ['Fire', 'Flying'],
            candy: 'None',
            candy_count: 0,
            immunes: [],
            strengths: ['Grass', 'Ice', 'Bug', 'Steel', 'Fighting'],
            weaknesses: ['Fire', 'Water', 'Rock', 'Dragon', 'Electric', 'Steel'],
            egg: 0,
            buddy: 5,
            next_evolution: [],
            prev_evolution: [],
            location: 'Unavailable'
        },
        {
            id: 147,
            name: 'Dratini',
            img: 'assets/images/pokemons/147.png',
            type: ['Dragon'],
            candy: 'Dratini Candy',
            candy_count: 0,
            immunes: [],
            strengths: ['Dragon'],
            weaknesses: ['Steel', 'Fairy'],
            egg: 10,
            buddy: 5,
            next_evolution: [148, 149],
            prev_evolution: [],
            location: ''
        },
        {
            id: 148,
            name: 'Dragonair',
            img: 'assets/images/pokemons/148.png',
            type: ['Dragon'],
            candy: 'Dratini Candy',
            candy_count: '25',
            immunes: [],
            strengths: ['Dragon'],
            weaknesses: ['Steel', 'Fairy'],
            egg: 0,
            buddy: 5,
            next_evolution: [149],
            prev_evolution: [147],
            location: ''
        },
        {
            id: 149,
            name: 'Dragonite',
            img: 'assets/images/pokemons/149.png',
            type: ['Dragon', 'Flying'],
            candy: 'Dratini Candy',
            candy_count: '100',
            immunes: [],
            strengths: ['Dragon', 'Grass', 'Fighting', 'Bug'],
            weaknesses: ['Steel', 'Fairy', 'Electric', 'Rock'],
            egg: 0,
            buddy: 5,
            next_evolution: [],
            prev_evolution: [147, 148],
            location: ''
        },
        {
            id: 150,
            name: 'Mewtwo',
            img: 'assets/images/pokemons/150.png',
            type: ['Psychic'],
            candy: 'None',
            candy_count: 0,
            immunes: [],
            strengths: ['Fighting', 'Poison'],
            weaknesses: ['Psychic', 'Steel', 'Dark'],
            egg: 0,
            buddy: 5,
            next_evolution: [],
            prev_evolution: [],
            location: 'Unavailable'
        },
        {
            id: 151,
            name: 'Mew',
            img: 'assets/images/pokemons/151.png',
            type: ['Psychic'],
            candy: 'None',
            candy_count: 0,
            immunes: [],
            strengths: ['Fighting', 'Poison'],
            weaknesses: ['Psychic', 'Steel', 'Dark'],
            egg: 0,
            buddy: 5,
            next_evolution: [],
            prev_evolution: [],
            location: 'Unavailable'
        }];

var pokemonSchema = new mongoose.Schema({
    id: { type: Number, unique: true },
    name: String,
    img: String,
    type: [String],
    candy: String,
    candy_count: Number,
    egg: Number,
    buddy: Number,
    multipliers: Number,
    immunes: [String],
    weaknesses: [String],
    strengths: [String],
    next_evolution: [Number],
    prev_evolution: [Number],
    location: String
});

pokemonSchema.virtual('keywords').get(function () {
    return [this.name, ("000" + this.id).slice(-3), this.type, this.egg + 'km', this.location];
});

pokemonSchema.set('toObject', {
    virtuals: true
});
pokemonSchema.set('toJSON', {
    virtuals: true
});

var PokemonDB = mongoose.model('Pokemon', pokemonSchema);
PokemonDB.collection.remove({});
PokemonDB.create(pokemonRawData, function (err) {
    if (err) {
        console.log(err);
    } else {
        PokemonDB.count({}, function (err, count) {
            if (err) console.log(err);
            console.log('%d pokemons were successfully loaded in PokemonDB.', count);
        });
    }
});

var getPokemon = function () {
    if (arguments.length === 1) {
        var callback = arguments[0];
        PokemonDB.find(function (err, pokemon) {
            if (err) callback(err);
            else callback(null, pokemon);
        });
    }
    else if (arguments.length === 2) {
        var id = arguments[0];
        var callback = arguments[1];
        PokemonDB.findOne({ 'id': id }, function (err, pokemon) {
            if (err) callback(err);
            else callback(null, pokemon);
        });
    }
};

module.exports.get = getPokemon;