var mongoose = require('./mongodb');

Array.prototype.unique = function () {
    var a = this.concat();
    for (var i = 0; i < a.length; ++i) {
        for (var j = i + 1; j < a.length; ++j) {
            if (a[i] === a[j])
                a.splice(j--, 1);
        }
    }
    return a;
};

var pokemonRawData =
    [{
        id: 1,
        name: 'Bulbasaur',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/001.png',
        type: ['Grass', 'Poison'],
        candy: 'Bulbasaur Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Water', 'Ground', 'Rock', 'Grass', 'Fairy'],
        weaknesses:
        ['Fire',
            'Grass',
            'Poison',
            'Flying',
            'Bug',
            'Dragon',
            'Steel',
            'Ground',
            'Rock',
            'Ghost'],
        egg: 2,
        buddy: 3,
        next_evolution: [2, 3],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/bulbasaur.gif'
    },
    {
        id: 2,
        name: 'Ivysaur',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/002.png',
        type: ['Grass', 'Poison'],
        candy: 'Bulbasaur Candy',
        candy_count: '25',
        immunes: [],
        strengths: ['Water', 'Ground', 'Rock', 'Grass', 'Fairy'],
        weaknesses:
        ['Fire',
            'Grass',
            'Poison',
            'Flying',
            'Bug',
            'Dragon',
            'Steel',
            'Ground',
            'Rock',
            'Ghost'],
        egg: 0,
        buddy: 3,
        next_evolution: [3],
        prev_evolution: [1],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/ivysaur.gif'
    },
    {
        id: 3,
        name: 'Venusaur',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/003.png',
        type: ['Grass', 'Poison'],
        candy: 'Bulbasaur Candy',
        candy_count: '100',
        immunes: [],
        strengths: ['Water', 'Ground', 'Rock', 'Grass', 'Fairy'],
        weaknesses:
        ['Fire',
            'Grass',
            'Poison',
            'Flying',
            'Bug',
            'Dragon',
            'Steel',
            'Ground',
            'Rock',
            'Ghost'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [1, 2],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/venusaur.gif'
    },
    {
        id: 4,
        name: 'Charmander',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/004.png',
        type: ['Fire'],
        candy: 'Charmander Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Grass', 'Ice', 'Bug', 'Steel'],
        weaknesses: ['Fire', 'Water', 'Rock', 'Dragon'],
        egg: 2,
        buddy: 3,
        next_evolution: [5, 6],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/charmander.gif'
    },
    {
        id: 5,
        name: 'Charmeleon',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/005.png',
        type: ['Fire'],
        candy: 'Charmander Candy',
        candy_count: '25',
        immunes: [],
        strengths: ['Grass', 'Ice', 'Bug', 'Steel'],
        weaknesses: ['Fire', 'Water', 'Rock', 'Dragon'],
        egg: 0,
        buddy: 3,
        next_evolution: [6],
        prev_evolution: [4],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/charmeleon.gif'
    },
    {
        id: 6,
        name: 'Charizard',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/006.png',
        type: ['Fire', 'Flying'],
        candy: 'Charmander Candy',
        candy_count: '100',
        immunes: [],
        strengths: ['Grass', 'Ice', 'Bug', 'Steel', 'Fighting'],
        weaknesses: ['Fire', 'Water', 'Rock', 'Dragon', 'Electric', 'Steel'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [4, 5],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/charizard.gif'
    },
    {
        id: 7,
        name: 'Squirtle',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/007.png',
        type: ['Water'],
        candy: 'Squirtle Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock'],
        weaknesses: ['Water', 'Grass', 'Dragon'],
        egg: 2,
        buddy: 3,
        next_evolution: [8, 9],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/squirtle.gif'
    },
    {
        id: 8,
        name: 'Wartortle',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/008.png',
        type: ['Water'],
        candy: 'Squirtle Candy',
        candy_count: '25',
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock'],
        weaknesses: ['Water', 'Grass', 'Dragon'],
        egg: 0,
        buddy: 3,
        next_evolution: [9],
        prev_evolution: [7],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/wartortle.gif'
    },
    {
        id: 9,
        name: 'Blastoise',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/009.png',
        type: ['Water'],
        candy: 'Squirtle Candy',
        candy_count: '100',
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock'],
        weaknesses: ['Water', 'Grass', 'Dragon'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [7, 8],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/blastoise.gif'
    },
    {
        id: 10,
        name: 'Caterpie',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/010.png',
        type: ['Bug'],
        candy: 'Caterpie Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Grass', 'Psychic', 'Dark'],
        weaknesses: ['Fire', 'Fighting', 'Poison', 'Flying', 'Ghost', 'Steel', 'Fairy'],
        egg: 2,
        buddy: 1,
        next_evolution: [11, 12],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/caterpie.gif'
    },
    {
        id: 11,
        name: 'Metapod',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/011.png',
        type: ['Bug'],
        candy: 'Caterpie Candy',
        candy_count: '12',
        immunes: [],
        strengths: ['Grass', 'Psychic', 'Dark'],
        weaknesses: ['Fire', 'Fighting', 'Poison', 'Flying', 'Ghost', 'Steel', 'Fairy'],
        egg: 0,
        buddy: 1,
        next_evolution: [12],
        prev_evolution: [10],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/metapod.gif'
    },
    {
        id: 12,
        name: 'Butterfree',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/012.png',
        type: ['Bug', 'Flying'],
        candy: 'Caterpie Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Grass', 'Psychic', 'Dark', 'Fighting', 'Bug'],
        weaknesses:
        ['Fire',
            'Fighting',
            'Poison',
            'Flying',
            'Ghost',
            'Steel',
            'Fairy',
            'Electric',
            'Rock'],
        egg: 0,
        buddy: 1,
        next_evolution: [],
        prev_evolution: [10, 11],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/butterfree.gif'
    },
    {
        id: 13,
        name: 'Weedle',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/013.png',
        type: ['Bug', 'Poison'],
        candy: 'Weedle Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Grass', 'Psychic', 'Dark', 'Fairy'],
        weaknesses:
        ['Fire',
            'Fighting',
            'Poison',
            'Flying',
            'Ghost',
            'Steel',
            'Fairy',
            'Ground',
            'Rock'],
        egg: 2,
        buddy: 1,
        next_evolution: [14, 15],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/weedle.gif'
    },
    {
        id: 14,
        name: 'Kakuna',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/014.png',
        type: ['Bug', 'Poison'],
        candy: 'Weedle Candy',
        candy_count: '12',
        immunes: [],
        strengths: ['Grass', 'Psychic', 'Dark', 'Fairy'],
        weaknesses:
        ['Fire',
            'Fighting',
            'Poison',
            'Flying',
            'Ghost',
            'Steel',
            'Fairy',
            'Ground',
            'Rock'],
        egg: 0,
        buddy: 1,
        next_evolution: [15],
        prev_evolution: [13],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/kakuna.gif'
    },
    {
        id: 15,
        name: 'Beedrill',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/015.png',
        type: ['Bug', 'Poison'],
        candy: 'Weedle Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Grass', 'Psychic', 'Dark', 'Fairy'],
        weaknesses:
        ['Fire',
            'Fighting',
            'Poison',
            'Flying',
            'Ghost',
            'Steel',
            'Fairy',
            'Ground',
            'Rock'],
        egg: 0,
        buddy: 1,
        next_evolution: [],
        prev_evolution: [13, 14],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/beedrill.gif'
    },
    {
        id: 16,
        name: 'Pidgey',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/016.png',
        type: ['Normal', 'Flying'],
        candy: 'Pidgey Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Grass', 'Fighting', 'Bug'],
        weaknesses: ['Rock', 'Steel', 'Ghost', 'Electric'],
        egg: 2,
        buddy: 1,
        next_evolution: [17, 18],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/pidgey.gif'
    },
    {
        id: 17,
        name: 'Pidgeotto',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/017.png',
        type: ['Normal', 'Flying'],
        candy: 'Pidgey Candy',
        candy_count: '12',
        immunes: [],
        strengths: ['Grass', 'Fighting', 'Bug'],
        weaknesses: ['Rock', 'Steel', 'Ghost', 'Electric'],
        egg: 0,
        buddy: 1,
        next_evolution: [18],
        prev_evolution: [16],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/pidgeotto.gif'
    },
    {
        id: 18,
        name: 'Pidgeot',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/018.png',
        type: ['Normal', 'Flying'],
        candy: 'Pidgey Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Grass', 'Fighting', 'Bug'],
        weaknesses: ['Rock', 'Steel', 'Ghost', 'Electric'],
        egg: 0,
        buddy: 1,
        next_evolution: [],
        prev_evolution: [16, 17],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/pidgeot.gif'
    },
    {
        id: 19,
        name: 'Rattata',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/019.png',
        type: ['Normal'],
        candy: 'Rattata Candy',
        candy_count: 0,
        immunes: [],
        strengths: [],
        weaknesses: ['Rock', 'Steel', 'Ghost'],
        egg: 2,
        buddy: 1,
        next_evolution: [20],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/rattata.gif'
    },
    {
        id: 20,
        name: 'Raticate',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/020.png',
        type: ['Normal'],
        candy: 'Rattata Candy',
        candy_count: '25',
        immunes: [],
        strengths: [],
        weaknesses: ['Rock', 'Steel', 'Ghost'],
        egg: 0,
        buddy: 1,
        next_evolution: [],
        prev_evolution: [19],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/raticate.gif'
    },
    {
        id: 21,
        name: 'Spearow',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/021.png',
        type: ['Normal', 'Flying'],
        candy: 'Spearow Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Grass', 'Fighting', 'Bug'],
        weaknesses: ['Rock', 'Steel', 'Ghost', 'Electric'],
        egg: 2,
        buddy: 1,
        next_evolution: [22],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/spearow.gif'
    },
    {
        id: 22,
        name: 'Fearow',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/022.png',
        type: ['Normal', 'Flying'],
        candy: 'Spearow Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Grass', 'Fighting', 'Bug'],
        weaknesses: ['Rock', 'Steel', 'Ghost', 'Electric'],
        egg: 0,
        buddy: 1,
        next_evolution: [],
        prev_evolution: [21],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/fearow.gif'
    },
    {
        id: 23,
        name: 'Ekans',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/023.png',
        type: ['Poison'],
        candy: 'Ekans Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Grass', 'Fairy'],
        weaknesses: ['Poison', 'Ground', 'Rock', 'Ghost', 'Steel'],
        egg: 5,
        buddy: 3,
        next_evolution: [24],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/ekans.gif'
    },
    {
        id: 24,
        name: 'Arbok',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/024.png',
        type: ['Poison'],
        candy: 'Ekans Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Grass', 'Fairy'],
        weaknesses: ['Poison', 'Ground', 'Rock', 'Ghost', 'Steel'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [23],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/arbok.gif'
    },
    {
        id: 25,
        name: 'Pikachu',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/025.png',
        type: ['Electric'],
        candy: 'Pikachu Candy',
        candy_count: '25',
        immunes: [],
        strengths: ['Water', 'Flying'],
        weaknesses: ['Electric', 'Grass', 'Dragon', 'Ground'],
        egg: 2,
        buddy: 1,
        next_evolution: [26],
        prev_evolution: [172],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/pikachu.gif'
    },
    {
        id: 26,
        name: 'Raichu',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/026.png',
        type: ['Electric'],
        candy: 'Pikachu Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Water', 'Flying'],
        weaknesses: ['Electric', 'Grass', 'Dragon', 'Ground'],
        egg: 0,
        buddy: 1,
        next_evolution: [],
        prev_evolution: [172, 25],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/raichu.gif'
    },
    {
        id: 27,
        name: 'Sandshrew',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/027.png',
        type: ['Ground'],
        candy: 'Sandshrew Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Fire', 'Electric', 'Poison', 'Rock', 'Steel'],
        weaknesses: ['Grass', 'Bug', 'Flying'],
        egg: 5,
        buddy: 3,
        next_evolution: [28],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/sandshrew.gif'
    },
    {
        id: 28,
        name: 'Sandslash',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/028.png',
        type: ['Ground'],
        candy: 'Sandshrew Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Fire', 'Electric', 'Poison', 'Rock', 'Steel'],
        weaknesses: ['Grass', 'Bug', 'Flying'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [27],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/sandslash.gif'
    },
    {
        id: 29,
        name: 'Nidoran♀',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/029.png',
        type: ['Poison'],
        candy: 'Nidoran♀ Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Grass', 'Fairy'],
        weaknesses: ['Poison', 'Ground', 'Rock', 'Ghost', 'Steel'],
        egg: 5,
        buddy: 3,
        next_evolution: [30, 31],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/nidoran_f.gif'
    },
    {
        id: 30,
        name: 'Nidorina',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/030.png',
        type: ['Poison'],
        candy: 'Nidoran♀ Candy',
        candy_count: '25',
        immunes: [],
        strengths: ['Grass', 'Fairy'],
        weaknesses: ['Poison', 'Ground', 'Rock', 'Ghost', 'Steel'],
        egg: 0,
        buddy: 3,
        next_evolution: [31],
        prev_evolution: [29],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/nidorina.gif'
    },
    {
        id: 31,
        name: 'Nidoqueen',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/031.png',
        type: ['Poison', 'Ground'],
        candy: 'Nidoran♀ Candy',
        candy_count: '100',
        immunes: [],
        strengths: ['Grass', 'Fairy', 'Fire', 'Electric', 'Poison', 'Rock', 'Steel'],
        weaknesses:
        ['Poison',
            'Ground',
            'Rock',
            'Ghost',
            'Steel',
            'Grass',
            'Bug',
            'Flying'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [29, 30],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/nidoqueen.gif'
    },
    {
        id: 32,
        name: 'Nidoran♂',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/032.png',
        type: ['Poison'],
        candy: 'Nidoran♂ Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Grass', 'Fairy'],
        weaknesses: ['Poison', 'Ground', 'Rock', 'Ghost', 'Steel'],
        egg: 5,
        buddy: 3,
        next_evolution: [33, 34],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/nidoran_m.gif'
    },
    {
        id: 33,
        name: 'Nidorino',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/033.png',
        type: ['Poison'],
        candy: 'Nidoran♂ Candy',
        candy_count: '25',
        immunes: [],
        strengths: ['Grass', 'Fairy'],
        weaknesses: ['Poison', 'Ground', 'Rock', 'Ghost', 'Steel'],
        egg: 0,
        buddy: 3,
        next_evolution: [34],
        prev_evolution: [32],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/nidorino.gif'
    },
    {
        id: 34,
        name: 'Nidoking',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/034.png',
        type: ['Poison', 'Ground'],
        candy: 'Nidoran♂ Candy',
        candy_count: '100',
        immunes: [],
        strengths: ['Grass', 'Fairy', 'Fire', 'Electric', 'Poison', 'Rock', 'Steel'],
        weaknesses:
        ['Poison',
            'Ground',
            'Rock',
            'Ghost',
            'Steel',
            'Grass',
            'Bug',
            'Flying'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [32, 33],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/nidoking.gif'
    },
    {
        id: 35,
        name: 'Clefairy',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/035.png',
        type: ['Fairy'],
        candy: 'Clefairy Candy',
        candy_count: '25',
        immunes: [],
        strengths: ['Fighting', 'Dragon', 'Dark'],
        weaknesses: ['Fire', 'Poison', 'Steel'],
        egg: 2,
        buddy: 1,
        next_evolution: [36],
        prev_evolution: [173],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/clefairy.gif'
    },
    {
        id: 36,
        name: 'Clefable',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/036.png',
        type: ['Fairy'],
        candy: 'Clefairy Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Fighting', 'Dragon', 'Dark'],
        weaknesses: ['Fire', 'Poison', 'Steel'],
        egg: 0,
        buddy: 1,
        next_evolution: [],
        prev_evolution: [173, 35],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/clefable.gif'
    },
    {
        id: 37,
        name: 'Vulpix',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/037.png',
        type: ['Fire'],
        candy: 'Vulpix Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Grass', 'Ice', 'Bug', 'Steel'],
        weaknesses: ['Fire', 'Water', 'Rock', 'Dragon'],
        egg: 5,
        buddy: 3,
        next_evolution: [38],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/vulpix.gif'
    },
    {
        id: 38,
        name: 'Ninetales',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/038.png',
        type: ['Fire'],
        candy: 'Vulpix Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Grass', 'Ice', 'Bug', 'Steel'],
        weaknesses: ['Fire', 'Water', 'Rock', 'Dragon'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [37],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/ninetales.gif'
    },
    {
        id: 39,
        name: 'Jigglypuff',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/039.png',
        type: ['Normal'],
        candy: 'Jigglypuff Candy',
        candy_count: '25',
        immunes: [],
        strengths: [],
        weaknesses: ['Rock', 'Steel', 'Ghost'],
        egg: 2,
        buddy: 1,
        next_evolution: [40],
        prev_evolution: [174],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/jigglypuff.gif'
    },
    {
        id: 40,
        name: 'Wigglytuff',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/040.png',
        type: ['Normal'],
        candy: 'Jigglypuff Candy',
        candy_count: '50',
        immunes: [],
        strengths: [],
        weaknesses: ['Rock', 'Steel', 'Ghost'],
        egg: 0,
        buddy: 1,
        next_evolution: [],
        prev_evolution: [174, 39],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/wigglytuff.gif'
    },
    {
        id: 41,
        name: 'Zubat',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/041.png',
        type: ['Poison', 'Flying'],
        candy: 'Zubat Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Grass', 'Fairy', 'Fighting', 'Bug'],
        weaknesses: ['Poison', 'Ground', 'Rock', 'Ghost', 'Steel', 'Electric'],
        egg: 2,
        buddy: 1,
        next_evolution: [42],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/zubat.gif'
    },
    {
        id: 42,
        name: 'Golbat',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/042.png',
        type: ['Poison', 'Flying'],
        candy: 'Zubat Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Grass', 'Fairy', 'Fighting', 'Bug'],
        weaknesses: ['Poison', 'Ground', 'Rock', 'Ghost', 'Steel', 'Electric'],
        egg: 0,
        buddy: 1,
        next_evolution: [],
        prev_evolution: [41],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/golbat.gif'
    },
    {
        id: 43,
        name: 'Oddish',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/043.png',
        type: ['Grass', 'Poison'],
        candy: 'Oddish Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Water', 'Ground', 'Rock', 'Grass', 'Fairy'],
        weaknesses:
        ['Fire',
            'Grass',
            'Poison',
            'Flying',
            'Bug',
            'Dragon',
            'Steel',
            'Ground',
            'Rock',
            'Ghost'],
        egg: 5,
        buddy: 3,
        next_evolution: [44, 45],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/oddish.gif'
    },
    {
        id: 44,
        name: 'Gloom',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/044.png',
        type: ['Grass', 'Poison'],
        candy: 'Oddish Candy',
        candy_count: '25',
        immunes: [],
        strengths: ['Water', 'Ground', 'Rock', 'Grass', 'Fairy'],
        weaknesses:
        ['Fire',
            'Grass',
            'Poison',
            'Flying',
            'Bug',
            'Dragon',
            'Steel',
            'Ground',
            'Rock',
            'Ghost'],
        egg: 0,
        buddy: 3,
        next_evolution: [45],
        prev_evolution: [43],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/gloom.gif'
    },
    {
        id: 45,
        name: 'Vileplume',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/045.png',
        type: ['Grass', 'Poison'],
        candy: 'Oddish Candy',
        candy_count: '100',
        immunes: [],
        strengths: ['Water', 'Ground', 'Rock', 'Grass', 'Fairy'],
        weaknesses:
        ['Fire',
            'Grass',
            'Poison',
            'Flying',
            'Bug',
            'Dragon',
            'Steel',
            'Ground',
            'Rock',
            'Ghost'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [43, 44],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/vileplume.gif'
    },
    {
        id: 46,
        name: 'Paras',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/046.png',
        type: ['Bug', 'Grass'],
        candy: 'Paras Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Grass', 'Psychic', 'Dark', 'Water', 'Ground', 'Rock'],
        weaknesses:
        ['Fire',
            'Fighting',
            'Poison',
            'Flying',
            'Ghost',
            'Steel',
            'Fairy',
            'Grass',
            'Bug',
            'Dragon'],
        egg: 5,
        buddy: 3,
        next_evolution: [47],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/paras.gif'
    },
    {
        id: 47,
        name: 'Parasect',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/047.png',
        type: ['Bug', 'Grass'],
        candy: 'Paras Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Grass', 'Psychic', 'Dark', 'Water', 'Ground', 'Rock'],
        weaknesses:
        ['Fire',
            'Fighting',
            'Poison',
            'Flying',
            'Ghost',
            'Steel',
            'Fairy',
            'Grass',
            'Bug',
            'Dragon'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [46],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/parasect.gif'
    },
    {
        id: 48,
        name: 'Venonat',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/048.png',
        type: ['Bug', 'Poison'],
        candy: 'Venonat Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Grass', 'Psychic', 'Dark', 'Fairy'],
        weaknesses:
        ['Fire',
            'Fighting',
            'Poison',
            'Flying',
            'Ghost',
            'Steel',
            'Fairy',
            'Ground',
            'Rock'],
        egg: 5,
        buddy: 3,
        next_evolution: [49],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/venonat.gif'
    },
    {
        id: 49,
        name: 'Venomoth',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/049.png',
        type: ['Bug', 'Poison'],
        candy: 'Venonat Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Grass', 'Psychic', 'Dark', 'Fairy'],
        weaknesses:
        ['Fire',
            'Fighting',
            'Poison',
            'Flying',
            'Ghost',
            'Steel',
            'Fairy',
            'Ground',
            'Rock'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [48],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/venomoth.gif'
    },
    {
        id: 50,
        name: 'Diglett',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/050.png',
        type: ['Ground'],
        candy: 'Diglett Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Fire', 'Electric', 'Poison', 'Rock', 'Steel'],
        weaknesses: ['Grass', 'Bug', 'Flying'],
        egg: 5,
        buddy: 3,
        next_evolution: [51],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/diglett.gif'
    },
    {
        id: 51,
        name: 'Dugtrio',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/051.png',
        type: ['Ground'],
        candy: 'Diglett Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Fire', 'Electric', 'Poison', 'Rock', 'Steel'],
        weaknesses: ['Grass', 'Bug', 'Flying'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [50],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/dugtrio.gif'
    },
    {
        id: 52,
        name: 'Meowth',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/052.png',
        type: ['Normal'],
        candy: 'Meowth Candy',
        candy_count: 0,
        immunes: [],
        strengths: [],
        weaknesses: ['Rock', 'Steel', 'Ghost'],
        egg: 5,
        buddy: 3,
        next_evolution: [53],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/meowth.gif'
    },
    {
        id: 53,
        name: 'Persian',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/053.png',
        type: ['Normal'],
        candy: 'Meowth Candy',
        candy_count: '50',
        immunes: [],
        strengths: [],
        weaknesses: ['Rock', 'Steel', 'Ghost'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [52],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/persian.gif'
    },
    {
        id: 54,
        name: 'Psyduck',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/054.png',
        type: ['Water'],
        candy: 'Psyduck Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock'],
        weaknesses: ['Water', 'Grass', 'Dragon'],
        egg: 5,
        buddy: 3,
        next_evolution: [55],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/psyduck.gif'
    },
    {
        id: 55,
        name: 'Golduck',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/055.png',
        type: ['Water'],
        candy: 'Psyduck Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock'],
        weaknesses: ['Water', 'Grass', 'Dragon'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [54],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/golduck.gif'
    },
    {
        id: 56,
        name: 'Mankey',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/056.png',
        type: ['Fighting'],
        candy: 'Mankey Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Normal', 'Ice', 'Rock', 'Dark', 'Steel'],
        weaknesses: ['Poison', 'Flying', 'Psychic', 'Bug', 'Fairy', 'Ghost'],
        egg: 5,
        buddy: 3,
        next_evolution: [57],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/mankey.gif'
    },
    {
        id: 57,
        name: 'Primeape',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/057.png',
        type: ['Fighting'],
        candy: 'Mankey Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Normal', 'Ice', 'Rock', 'Dark', 'Steel'],
        weaknesses: ['Poison', 'Flying', 'Psychic', 'Bug', 'Fairy', 'Ghost'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [56],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/primeape.gif'
    },
    {
        id: 58,
        name: 'Growlithe',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/058.png',
        type: ['Fire'],
        candy: 'Growlithe Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Grass', 'Ice', 'Bug', 'Steel'],
        weaknesses: ['Fire', 'Water', 'Rock', 'Dragon'],
        egg: 5,
        buddy: 3,
        next_evolution: [59],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/growlithe.gif'
    },
    {
        id: 59,
        name: 'Arcanine',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/059.png',
        type: ['Fire'],
        candy: 'Growlithe Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Grass', 'Ice', 'Bug', 'Steel'],
        weaknesses: ['Fire', 'Water', 'Rock', 'Dragon'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [58],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/arcanine.gif'
    },
    {
        id: 60,
        name: 'Poliwag',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/060.png',
        type: ['Water'],
        candy: 'Poliwag Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock'],
        weaknesses: ['Water', 'Grass', 'Dragon'],
        egg: 5,
        buddy: 3,
        next_evolution: [61, 62],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/poliwag.gif'
    },
    {
        id: 61,
        name: 'Poliwhirl',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/061.png',
        type: ['Water'],
        candy: 'Poliwag Candy',
        candy_count: '25',
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock'],
        weaknesses: ['Water', 'Grass', 'Dragon'],
        egg: 0,
        buddy: 3,
        next_evolution: [62],
        prev_evolution: [60],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/poliwhirl.gif'
    },
    {
        id: 62,
        name: 'Poliwrath',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/062.png',
        type: ['Water', 'Fighting'],
        candy: 'Poliwag Candy',
        candy_count: '100',
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock', 'Normal', 'Ice', 'Dark', 'Steel'],
        weaknesses:
        ['Water',
            'Grass',
            'Dragon',
            'Poison',
            'Flying',
            'Psychic',
            'Bug',
            'Fairy',
            'Ghost'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [60, 61],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/poliwrath.gif'
    },
    {
        id: 63,
        name: 'Abra',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/063.png',
        type: ['Psychic'],
        candy: 'Abra Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Fighting', 'Poison'],
        weaknesses: ['Psychic', 'Steel', 'Dark'],
        egg: 5,
        buddy: 3,
        next_evolution: [64, 65],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/abra.gif'
    },
    {
        id: 64,
        name: 'Kadabra',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/064.png',
        type: ['Psychic'],
        candy: 'Abra Candy',
        candy_count: '25',
        immunes: [],
        strengths: ['Fighting', 'Poison'],
        weaknesses: ['Psychic', 'Steel', 'Dark'],
        egg: 0,
        buddy: 3,
        next_evolution: [65],
        prev_evolution: [63],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/kadabra.gif'
    },
    {
        id: 65,
        name: 'Alakazam',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/065.png',
        type: ['Psychic'],
        candy: 'Abra Candy',
        candy_count: '100',
        immunes: [],
        strengths: ['Fighting', 'Poison'],
        weaknesses: ['Psychic', 'Steel', 'Dark'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [63, 64],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/alakazam.gif'
    },
    {
        id: 66,
        name: 'Machop',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/066.png',
        type: ['Fighting'],
        candy: 'Machop Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Normal', 'Ice', 'Rock', 'Dark', 'Steel'],
        weaknesses: ['Poison', 'Flying', 'Psychic', 'Bug', 'Fairy', 'Ghost'],
        egg: 5,
        buddy: 3,
        next_evolution: [67, 68],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/machop.gif'
    },
    {
        id: 67,
        name: 'Machoke',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/067.png',
        type: ['Fighting'],
        candy: 'Machop Candy',
        candy_count: '25',
        immunes: [],
        strengths: ['Normal', 'Ice', 'Rock', 'Dark', 'Steel'],
        weaknesses: ['Poison', 'Flying', 'Psychic', 'Bug', 'Fairy', 'Ghost'],
        egg: 0,
        buddy: 3,
        next_evolution: [68],
        prev_evolution: [66],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/machoke.gif'
    },
    {
        id: 68,
        name: 'Machamp',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/068.png',
        type: ['Fighting'],
        candy: 'Machop Candy',
        candy_count: '100',
        immunes: [],
        strengths: ['Normal', 'Ice', 'Rock', 'Dark', 'Steel'],
        weaknesses: ['Poison', 'Flying', 'Psychic', 'Bug', 'Fairy', 'Ghost'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [66, 67],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/machamp.gif'
    },
    {
        id: 69,
        name: 'Bellsprout',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/069.png',
        type: ['Grass', 'Poison'],
        candy: 'Bellsprout Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Water', 'Ground', 'Rock', 'Grass', 'Fairy'],
        weaknesses:
        ['Fire',
            'Grass',
            'Poison',
            'Flying',
            'Bug',
            'Dragon',
            'Steel',
            'Ground',
            'Rock',
            'Ghost'],
        egg: 5,
        buddy: 3,
        next_evolution: [70, 71],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/bellsprout.gif'
    },
    {
        id: 70,
        name: 'Weepinbell',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/070.png',
        type: ['Grass', 'Poison'],
        candy: 'Bellsprout Candy',
        candy_count: '25',
        immunes: [],
        strengths: ['Water', 'Ground', 'Rock', 'Grass', 'Fairy'],
        weaknesses:
        ['Fire',
            'Grass',
            'Poison',
            'Flying',
            'Bug',
            'Dragon',
            'Steel',
            'Ground',
            'Rock',
            'Ghost'],
        egg: 0,
        buddy: 3,
        next_evolution: [71],
        prev_evolution: [69],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/weepinbell.gif'
    },
    {
        id: 71,
        name: 'Victreebel',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/071.png',
        type: ['Grass', 'Poison'],
        candy: 'Bellsprout Candy',
        candy_count: '100',
        immunes: [],
        strengths: ['Water', 'Ground', 'Rock', 'Grass', 'Fairy'],
        weaknesses:
        ['Fire',
            'Grass',
            'Poison',
            'Flying',
            'Bug',
            'Dragon',
            'Steel',
            'Ground',
            'Rock',
            'Ghost'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [69, 70],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/victreebel.gif'
    },
    {
        id: 72,
        name: 'Tentacool',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/072.png',
        type: ['Water', 'Poison'],
        candy: 'Tentacool Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock', 'Grass', 'Fairy'],
        weaknesses:
        ['Water',
            'Grass',
            'Dragon',
            'Poison',
            'Ground',
            'Rock',
            'Ghost',
            'Steel'],
        egg: 5,
        buddy: 3,
        next_evolution: [73],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/tentacool.gif'
    },
    {
        id: 73,
        name: 'Tentacruel',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/073.png',
        type: ['Water', 'Poison'],
        candy: 'Tentacool Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock', 'Grass', 'Fairy'],
        weaknesses:
        ['Water',
            'Grass',
            'Dragon',
            'Poison',
            'Ground',
            'Rock',
            'Ghost',
            'Steel'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [72],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/tentacruel.gif'
    },
    {
        id: 74,
        name: 'Geodude',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/074.png',
        type: ['Rock', 'Ground'],
        candy: 'Geodude Candy',
        candy_count: 0,
        immunes: [],
        strengths:
        ['Fire',
            'Ice',
            'Flying',
            'Bug',
            'Electric',
            'Poison',
            'Rock',
            'Steel'],
        weaknesses: ['Fighting', 'Ground', 'Steel', 'Grass', 'Bug', 'Flying'],
        egg: 2,
        buddy: 1,
        next_evolution: [75, 76],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/geodude.gif'
    },
    {
        id: 75,
        name: 'Graveler',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/075.png',
        type: ['Rock', 'Ground'],
        candy: 'Geodude Candy',
        candy_count: '25',
        immunes: [],
        strengths:
        ['Fire',
            'Ice',
            'Flying',
            'Bug',
            'Electric',
            'Poison',
            'Rock',
            'Steel'],
        weaknesses: ['Fighting', 'Ground', 'Steel', 'Grass', 'Bug', 'Flying'],
        egg: 0,
        buddy: 1,
        next_evolution: [76],
        prev_evolution: [74],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/graveler.gif'
    },
    {
        id: 76,
        name: 'Golem',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/076.png',
        type: ['Rock', 'Ground'],
        candy: 'Geodude Candy',
        candy_count: '100',
        immunes: [],
        strengths:
        ['Fire',
            'Ice',
            'Flying',
            'Bug',
            'Electric',
            'Poison',
            'Rock',
            'Steel'],
        weaknesses: ['Fighting', 'Ground', 'Steel', 'Grass', 'Bug', 'Flying'],
        egg: 0,
        buddy: 1,
        next_evolution: [],
        prev_evolution: [74, 75],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/golem.gif'
    },
    {
        id: 77,
        name: 'Ponyta',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/077.png',
        type: ['Fire'],
        candy: 'Ponyta Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Grass', 'Ice', 'Bug', 'Steel'],
        weaknesses: ['Fire', 'Water', 'Rock', 'Dragon'],
        egg: 5,
        buddy: 3,
        next_evolution: [78],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/ponyta.gif'
    },
    {
        id: 78,
        name: 'Rapidash',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/078.png',
        type: ['Fire'],
        candy: 'Ponyta Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Grass', 'Ice', 'Bug', 'Steel'],
        weaknesses: ['Fire', 'Water', 'Rock', 'Dragon'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [77],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/rapidash.gif'
    },
    {
        id: 79,
        name: 'Slowpoke',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/079.png',
        type: ['Water', 'Psychic'],
        candy: 'Slowpoke Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock', 'Fighting', 'Poison'],
        weaknesses: ['Water', 'Grass', 'Dragon', 'Psychic', 'Steel', 'Dark'],
        egg: 5,
        buddy: 3,
        next_evolution: [80],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/slowpoke.gif'
    },
    {
        id: 80,
        name: 'Slowbro',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/080.png',
        type: ['Water', 'Psychic'],
        candy: 'Slowpoke Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock', 'Fighting', 'Poison'],
        weaknesses: ['Water', 'Grass', 'Dragon', 'Psychic', 'Steel', 'Dark'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [79],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/slowbro.gif'
    },
    {
        id: 81,
        name: 'Magnemite',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/081.png',
        type: ['Electric', 'Steel'],
        candy: 'Magnemite Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Water', 'Flying'],
        weaknesses: ['Electric', 'Grass', 'Dragon', 'Ground'],
        egg: 5,
        buddy: 3,
        next_evolution: [82],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/magnemite.gif'
    },
    {
        id: 82,
        name: 'Magneton',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/082.png',
        type: ['Electric', 'Steel'],
        candy: 'Magnemite Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Water', 'Flying'],
        weaknesses: ['Electric', 'Grass', 'Dragon', 'Ground'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [81],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/magneton.gif'
    },
    {
        id: 83,
        name: 'Farfetch\'d',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/083.png',
        type: ['Normal', 'Flying'],
        candy: 'Farfetch\'d Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Grass', 'Fighting', 'Bug'],
        weaknesses: ['Rock', 'Steel', 'Ghost', 'Electric'],
        egg: 5,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [],
        location: 'Asia',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/farfetch\'d.gif'
    },
    {
        id: 84,
        name: 'Doduo',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/084.png',
        type: ['Normal', 'Flying'],
        candy: 'Doduo Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Grass', 'Fighting', 'Bug'],
        weaknesses: ['Rock', 'Steel', 'Ghost', 'Electric'],
        egg: 5,
        buddy: 3,
        next_evolution: [85],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/doduo.gif'
    },
    {
        id: 85,
        name: 'Dodrio',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/085.png',
        type: ['Normal', 'Flying'],
        candy: 'Doduo Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Grass', 'Fighting', 'Bug'],
        weaknesses: ['Rock', 'Steel', 'Ghost', 'Electric'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [84],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/dodrio.gif'
    },
    {
        id: 86,
        name: 'Seel',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/086.png',
        type: ['Water'],
        candy: 'Seel Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock'],
        weaknesses: ['Water', 'Grass', 'Dragon'],
        egg: 5,
        buddy: 3,
        next_evolution: [87],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/seel.gif'
    },
    {
        id: 87,
        name: 'Dewgong',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/087.png',
        type: ['Water', 'Ice'],
        candy: 'Seel Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock', 'Grass', 'Flying', 'Dragon'],
        weaknesses: ['Water', 'Grass', 'Dragon', 'Fire', 'Ice', 'Steel'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [86],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/dewgong.gif'
    },
    {
        id: 88,
        name: 'Grimer',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/088.png',
        type: ['Poison'],
        candy: 'Grimer Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Grass', 'Fairy'],
        weaknesses: ['Poison', 'Ground', 'Rock', 'Ghost', 'Steel'],
        egg: 5,
        buddy: 3,
        next_evolution: [89],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/grimer.gif'
    },
    {
        id: 89,
        name: 'Muk',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/089.png',
        type: ['Poison'],
        candy: 'Grimer Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Grass', 'Fairy'],
        weaknesses: ['Poison', 'Ground', 'Rock', 'Ghost', 'Steel'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [88],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/muk.gif'
    },
    {
        id: 90,
        name: 'Shellder',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/090.png',
        type: ['Water'],
        candy: 'Shellder Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock'],
        weaknesses: ['Water', 'Grass', 'Dragon'],
        egg: 5,
        buddy: 3,
        next_evolution: [91],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/shellder.gif'
    },
    {
        id: 91,
        name: 'Cloyster',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/091.png',
        type: ['Water', 'Ice'],
        candy: 'Shellder Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock', 'Grass', 'Flying', 'Dragon'],
        weaknesses: ['Water', 'Grass', 'Dragon', 'Fire', 'Ice', 'Steel'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [90],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/cloyster.gif'
    },
    {
        id: 92,
        name: 'Gastly',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/092.png',
        type: ['Ghost', 'Poison'],
        candy: 'Gastly Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Psychic', 'Ghost', 'Grass', 'Fairy'],
        weaknesses: ['Dark', 'Normal', 'Poison', 'Ground', 'Rock', 'Ghost', 'Steel'],
        egg: 5,
        buddy: 3,
        next_evolution: [93, 94],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/gastly.gif'
    },
    {
        id: 93,
        name: 'Haunter',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/093.png',
        type: ['Ghost', 'Poison'],
        candy: 'Gastly Candy',
        candy_count: '25',
        immunes: [],
        strengths: ['Psychic', 'Ghost', 'Grass', 'Fairy'],
        weaknesses: ['Dark', 'Normal', 'Poison', 'Ground', 'Rock', 'Ghost', 'Steel'],
        egg: 0,
        buddy: 3,
        next_evolution: [94],
        prev_evolution: [92],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/haunter.gif'
    },
    {
        id: 94,
        name: 'Gengar',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/094.png',
        type: ['Ghost', 'Poison'],
        candy: 'Gastly Candy',
        candy_count: '100',
        immunes: [],
        strengths: ['Psychic', 'Ghost', 'Grass', 'Fairy'],
        weaknesses: ['Dark', 'Normal', 'Poison', 'Ground', 'Rock', 'Ghost', 'Steel'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [92, 93],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/gengar.gif'
    },
    {
        id: 95,
        name: 'Onix',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/095.png',
        type: ['Rock', 'Ground'],
        candy: 'Onix Candy',
        candy_count: 0,
        immunes: [],
        strengths:
        ['Fire',
            'Ice',
            'Flying',
            'Bug',
            'Electric',
            'Poison',
            'Rock',
            'Steel'],
        weaknesses: ['Fighting', 'Ground', 'Steel', 'Grass', 'Bug', 'Flying'],
        egg: 10,
        buddy: 5,
        next_evolution: [],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/onix.gif'
    },
    {
        id: 96,
        name: 'Drowzee',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/096.png',
        type: ['Psychic'],
        candy: 'Drowzee Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Fighting', 'Poison'],
        weaknesses: ['Psychic', 'Steel', 'Dark'],
        egg: 5,
        buddy: 3,
        next_evolution: [97],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/drowzee.gif'
    },
    {
        id: 97,
        name: 'Hypno',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/097.png',
        type: ['Psychic'],
        candy: 'Drowzee Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Fighting', 'Poison'],
        weaknesses: ['Psychic', 'Steel', 'Dark'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [96],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/hypno.gif'
    },
    {
        id: 98,
        name: 'Krabby',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/098.png',
        type: ['Water'],
        candy: 'Krabby Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock'],
        weaknesses: ['Water', 'Grass', 'Dragon'],
        egg: 5,
        buddy: 3,
        next_evolution: [99],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/krabby.gif'
    },
    {
        id: 99,
        name: 'Kingler',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/099.png',
        type: ['Water'],
        candy: 'Krabby Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock'],
        weaknesses: ['Water', 'Grass', 'Dragon'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [98],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/kingler.gif'
    },
    {
        id: 100,
        name: 'Voltorb',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/100.png',
        type: ['Electric'],
        candy: 'Voltorb Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Water', 'Flying'],
        weaknesses: ['Electric', 'Grass', 'Dragon', 'Ground'],
        egg: 5,
        buddy: 3,
        next_evolution: [101],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/voltorb.gif'
    },
    {
        id: 101,
        name: 'Electrode',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/101.png',
        type: ['Electric'],
        candy: 'Voltorb Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Water', 'Flying'],
        weaknesses: ['Electric', 'Grass', 'Dragon', 'Ground'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [100],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/electrode.gif'
    },
    {
        id: 102,
        name: 'Exeggcute',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/102.png',
        type: ['Grass', 'Psychic'],
        candy: 'Exeggcute Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Water', 'Ground', 'Rock', 'Fighting', 'Poison'],
        weaknesses:
        ['Fire',
            'Grass',
            'Poison',
            'Flying',
            'Bug',
            'Dragon',
            'Steel',
            'Psychic',
            'Dark'],
        egg: 5,
        buddy: 3,
        next_evolution: [103],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/exeggcute.gif'
    },
    {
        id: 103,
        name: 'Exeggutor',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/103.png',
        type: ['Grass', 'Psychic'],
        candy: 'Exeggcute Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Water', 'Ground', 'Rock', 'Fighting', 'Poison'],
        weaknesses:
        ['Fire',
            'Grass',
            'Poison',
            'Flying',
            'Bug',
            'Dragon',
            'Steel',
            'Psychic',
            'Dark'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [102],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/exeggutor.gif'
    },
    {
        id: 104,
        name: 'Cubone',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/104.png',
        type: ['Ground'],
        candy: 'Cubone Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Fire', 'Electric', 'Poison', 'Rock', 'Steel'],
        weaknesses: ['Grass', 'Bug', 'Flying'],
        egg: 5,
        buddy: 3,
        next_evolution: [105],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/cubone.gif'
    },
    {
        id: 105,
        name: 'Marowak',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/105.png',
        type: ['Ground'],
        candy: 'Cubone Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Fire', 'Electric', 'Poison', 'Rock', 'Steel'],
        weaknesses: ['Grass', 'Bug', 'Flying'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [104],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/marowak.gif'
    },
    {
        id: 106,
        name: 'Hitmonlee',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/106.png',
        type: ['Fighting'],
        candy: 'Hitmonlee Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Normal', 'Ice', 'Rock', 'Dark', 'Steel'],
        weaknesses: ['Poison', 'Flying', 'Psychic', 'Bug', 'Fairy', 'Ghost'],
        egg: 10,
        buddy: 5,
        next_evolution: [],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/hitmonlee.gif'
    },
    {
        id: 107,
        name: 'Hitmonchan',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/107.png',
        type: ['Fighting'],
        candy: 'Hitmonchan Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Normal', 'Ice', 'Rock', 'Dark', 'Steel'],
        weaknesses: ['Poison', 'Flying', 'Psychic', 'Bug', 'Fairy', 'Ghost'],
        egg: 10,
        buddy: 5,
        next_evolution: [],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/hitmonchan.gif'
    },
    {
        id: 108,
        name: 'Lickitung',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/108.png',
        type: ['Normal'],
        candy: 'Lickitung Candy',
        candy_count: 0,
        immunes: [],
        strengths: [],
        weaknesses: ['Rock', 'Steel', 'Ghost'],
        egg: 5,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/lickitung.gif'
    },
    {
        id: 109,
        name: 'Koffing',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/109.png',
        type: ['Poison'],
        candy: 'Koffing Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Grass', 'Fairy'],
        weaknesses: ['Poison', 'Ground', 'Rock', 'Ghost', 'Steel'],
        egg: 5,
        buddy: 3,
        next_evolution: [110],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/koffing.gif'
    },
    {
        id: 110,
        name: 'Weezing',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/110.png',
        type: ['Poison'],
        candy: 'Koffing Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Grass', 'Fairy'],
        weaknesses: ['Poison', 'Ground', 'Rock', 'Ghost', 'Steel'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [109],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/weezing.gif'
    },
    {
        id: 111,
        name: 'Rhyhorn',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/111.png',
        type: ['Ground', 'Rock'],
        candy: 'Rhyhorn Candy',
        candy_count: 0,
        immunes: [],
        strengths:
        ['Fire',
            'Electric',
            'Poison',
            'Rock',
            'Steel',
            'Ice',
            'Flying',
            'Bug'],
        weaknesses: ['Grass', 'Bug', 'Flying', 'Fighting', 'Ground', 'Steel'],
        egg: 5,
        buddy: 3,
        next_evolution: [112],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/rhyhorn.gif'
    },
    {
        id: 112,
        name: 'Rhydon',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/112.png',
        type: ['Ground', 'Rock'],
        candy: 'Rhyhorn Candy',
        candy_count: '50',
        immunes: [],
        strengths:
        ['Fire',
            'Electric',
            'Poison',
            'Rock',
            'Steel',
            'Ice',
            'Flying',
            'Bug'],
        weaknesses: ['Grass', 'Bug', 'Flying', 'Fighting', 'Ground', 'Steel'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [111],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/rhydon.gif'
    },
    {
        id: 113,
        name: 'Chansey',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/113.png',
        type: ['Normal'],
        candy: 'Chansey Candy',
        candy_count: 0,
        immunes: [],
        strengths: [],
        weaknesses: ['Rock', 'Steel', 'Ghost'],
        egg: 10,
        buddy: 5,
        next_evolution: [],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/chansey.gif'
    },
    {
        id: 114,
        name: 'Tangela',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/114.png',
        type: ['Grass'],
        candy: 'Tangela Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Water', 'Ground', 'Rock'],
        weaknesses: ['Fire', 'Grass', 'Poison', 'Flying', 'Bug', 'Dragon', 'Steel'],
        egg: 5,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/tangela.gif'
    },
    {
        id: 115,
        name: 'Kangaskhan',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/115.png',
        type: ['Normal'],
        candy: 'Kangaskhan Candy',
        candy_count: 0,
        immunes: [],
        strengths: [],
        weaknesses: ['Rock', 'Steel', 'Ghost'],
        egg: 5,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [],
        location: 'Australia',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/kangaskhan.gif'
    },
    {
        id: 116,
        name: 'Horsea',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/116.png',
        type: ['Water'],
        candy: 'Horsea Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock'],
        weaknesses: ['Water', 'Grass', 'Dragon'],
        egg: 5,
        buddy: 3,
        next_evolution: [117],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/horsea.gif'
    },
    {
        id: 117,
        name: 'Seadra',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/117.png',
        type: ['Water'],
        candy: 'Horsea Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock'],
        weaknesses: ['Water', 'Grass', 'Dragon'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [116],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/seadra.gif'
    },
    {
        id: 118,
        name: 'Goldeen',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/118.png',
        type: ['Water'],
        candy: 'Goldeen Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock'],
        weaknesses: ['Water', 'Grass', 'Dragon'],
        egg: 5,
        buddy: 3,
        next_evolution: [119],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/goldeen.gif'
    },
    {
        id: 119,
        name: 'Seaking',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/119.png',
        type: ['Water'],
        candy: 'Goldeen Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock'],
        weaknesses: ['Water', 'Grass', 'Dragon'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [118],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/seaking.gif'
    },
    {
        id: 120,
        name: 'Staryu',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/120.png',
        type: ['Water'],
        candy: 'Staryu Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock'],
        weaknesses: ['Water', 'Grass', 'Dragon'],
        egg: 5,
        buddy: 3,
        next_evolution: [121],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/staryu.gif'
    },
    {
        id: 121,
        name: 'Starmie',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/121.png',
        type: ['Water', 'Psychic'],
        candy: 'Staryu Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock', 'Fighting', 'Poison'],
        weaknesses: ['Water', 'Grass', 'Dragon', 'Psychic', 'Steel', 'Dark'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [120],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/starmie.gif'
    },
    {
        id: 122,
        name: 'Mr. Mime',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/122.png',
        type: ['Psychic'],
        candy: 'Mr. Mime Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Fighting', 'Poison'],
        weaknesses: ['Psychic', 'Steel', 'Dark'],
        egg: 10,
        buddy: 5,
        next_evolution: [],
        prev_evolution: [],
        location: 'Europe',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/mr._mime.gif'
    },
    {
        id: 123,
        name: 'Scyther',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/123.png',
        type: ['Bug', 'Flying'],
        candy: 'Scyther Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Grass', 'Psychic', 'Dark', 'Fighting', 'Bug'],
        weaknesses:
        ['Fire',
            'Fighting',
            'Poison',
            'Flying',
            'Ghost',
            'Steel',
            'Fairy',
            'Electric',
            'Rock'],
        egg: 10,
        buddy: 5,
        next_evolution: [],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/scyther.gif'
    },
    {
        id: 124,
        name: 'Jynx',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/124.png',
        type: ['Ice', 'Psychic'],
        candy: 'Jynx Candy',
        candy_count: '25',
        immunes: [],
        strengths: ['Grass', 'Ground', 'Flying', 'Dragon', 'Fighting', 'Poison'],
        weaknesses: ['Fire', 'Water', 'Ice', 'Steel', 'Psychic', 'Dark'],
        egg: 10,
        buddy: 5,
        next_evolution: [],
        prev_evolution: [238],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/jynx.gif'
    },
    {
        id: 125,
        name: 'Electabuzz',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/125.png',
        type: ['Electric'],
        candy: 'Electabuzz Candy',
        candy_count: '25',
        immunes: [],
        strengths: ['Water', 'Flying'],
        weaknesses: ['Electric', 'Grass', 'Dragon', 'Ground'],
        egg: 10,
        buddy: 5,
        next_evolution: [],
        prev_evolution: [239],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/electabuzz.gif'
    },
    {
        id: 126,
        name: 'Magmar',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/126.png',
        type: ['Fire'],
        candy: 'Magmar Candy',
        candy_count: '25',
        immunes: [],
        strengths: ['Grass', 'Ice', 'Bug', 'Steel'],
        weaknesses: ['Fire', 'Water', 'Rock', 'Dragon'],
        egg: 10,
        buddy: 5,
        next_evolution: [],
        prev_evolution: [240],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/magmar.gif'
    },
    {
        id: 127,
        name: 'Pinsir',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/127.png',
        type: ['Bug'],
        candy: 'Pinsir Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Grass', 'Psychic', 'Dark'],
        weaknesses: ['Fire', 'Fighting', 'Poison', 'Flying', 'Ghost', 'Steel', 'Fairy'],
        egg: 10,
        buddy: 5,
        next_evolution: [],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/pinsir.gif'
    },
    {
        id: 128,
        name: 'Tauros',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/128.png',
        type: ['Normal'],
        candy: 'Tauros Candy',
        candy_count: 0,
        immunes: [],
        strengths: [],
        weaknesses: ['Rock', 'Steel', 'Ghost'],
        egg: 5,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [],
        location: 'North America',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/tauros.gif'
    },
    {
        id: 129,
        name: 'Magikarp',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/129.png',
        type: ['Water'],
        candy: 'Magikarp Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock'],
        weaknesses: ['Water', 'Grass', 'Dragon'],
        egg: 2,
        buddy: 1,
        next_evolution: [130],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/magikarp.gif'
    },
    {
        id: 130,
        name: 'Gyarados',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/130.png',
        type: ['Water', 'Flying'],
        candy: 'Magikarp Candy',
        candy_count: '400',
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock', 'Grass', 'Fighting', 'Bug'],
        weaknesses: ['Water', 'Grass', 'Dragon', 'Electric', 'Rock', 'Steel'],
        egg: 0,
        buddy: 1,
        next_evolution: [],
        prev_evolution: [129],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/gyarados.gif'
    },
    {
        id: 131,
        name: 'Lapras',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/131.png',
        type: ['Water', 'Ice'],
        candy: 'Lapras Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock', 'Grass', 'Flying', 'Dragon'],
        weaknesses: ['Water', 'Grass', 'Dragon', 'Fire', 'Ice', 'Steel'],
        egg: 10,
        buddy: 5,
        next_evolution: [],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/lapras.gif'
    },
    {
        id: 132,
        name: 'Ditto',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/132.png',
        type: ['Normal'],
        candy: 'None',
        candy_count: 0,
        immunes: [],
        strengths: [],
        weaknesses: ['Rock', 'Steel', 'Ghost'],
        egg: 0,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [],
        location: 'Unavailable',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/ditto.gif'
    },
    {
        id: 133,
        name: 'Eevee',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/133.png',
        type: ['Normal'],
        candy: 'Eevee Candy',
        candy_count: 0,
        immunes: [],
        strengths: [],
        weaknesses: ['Rock', 'Steel', 'Ghost'],
        egg: 10,
        buddy: 5,
        next_evolution: [134, 135, 136],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/eevee.gif'
    },
    {
        id: 134,
        name: 'Vaporeon',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/134.png',
        type: ['Water'],
        candy: 'Eevee Candy',
        candy_count: '25',
        immunes: [],
        strengths: ['Fire', 'Ground', 'Rock'],
        weaknesses: ['Water', 'Grass', 'Dragon'],
        egg: 0,
        buddy: 5,
        next_evolution: [],
        prev_evolution: [133],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/vaporeon.gif'
    },
    {
        id: 135,
        name: 'Jolteon',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/135.png',
        type: ['Electric'],
        candy: 'Eevee Candy',
        candy_count: '25',
        immunes: [],
        strengths: ['Water', 'Flying'],
        weaknesses: ['Electric', 'Grass', 'Dragon', 'Ground'],
        egg: 0,
        buddy: 5,
        next_evolution: [],
        prev_evolution: [133],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/jolteon.gif'
    },
    {
        id: 136,
        name: 'Flareon',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/136.png',
        type: ['Fire'],
        candy: 'Eevee Candy',
        candy_count: '25',
        immunes: [],
        strengths: ['Grass', 'Ice', 'Bug', 'Steel'],
        weaknesses: ['Fire', 'Water', 'Rock', 'Dragon'],
        egg: 0,
        buddy: 5,
        next_evolution: [],
        prev_evolution: [133],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/flareon.gif'
    },
    {
        id: 137,
        name: 'Porygon',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/137.png',
        type: ['Normal'],
        candy: 'Porygon Candy',
        candy_count: 0,
        immunes: [],
        strengths: [],
        weaknesses: ['Rock', 'Steel', 'Ghost'],
        egg: 5,
        buddy: 3,
        next_evolution: [],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/porygon.gif'
    },
    {
        id: 138,
        name: 'Omanyte',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/138.png',
        type: ['Rock', 'Water'],
        candy: 'Omanyte Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Fire', 'Ice', 'Flying', 'Bug', 'Ground', 'Rock'],
        weaknesses: ['Fighting', 'Ground', 'Steel', 'Water', 'Grass', 'Dragon'],
        egg: 10,
        buddy: 5,
        next_evolution: [139],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/omanyte.gif'
    },
    {
        id: 139,
        name: 'Omastar',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/139.png',
        type: ['Rock', 'Water'],
        candy: 'Omanyte Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Fire', 'Ice', 'Flying', 'Bug', 'Ground', 'Rock'],
        weaknesses: ['Fighting', 'Ground', 'Steel', 'Water', 'Grass', 'Dragon'],
        egg: 0,
        buddy: 5,
        next_evolution: [],
        prev_evolution: [138],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/omastar.gif'
    },
    {
        id: 140,
        name: 'Kabuto',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/140.png',
        type: ['Rock', 'Water'],
        candy: 'Kabuto Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Fire', 'Ice', 'Flying', 'Bug', 'Ground', 'Rock'],
        weaknesses: ['Fighting', 'Ground', 'Steel', 'Water', 'Grass', 'Dragon'],
        egg: 10,
        buddy: 5,
        next_evolution: [141],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/kabuto.gif'
    },
    {
        id: 141,
        name: 'Kabutops',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/141.png',
        type: ['Rock', 'Water'],
        candy: 'Kabuto Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Fire', 'Ice', 'Flying', 'Bug', 'Ground', 'Rock'],
        weaknesses: ['Fighting', 'Ground', 'Steel', 'Water', 'Grass', 'Dragon'],
        egg: 0,
        buddy: 5,
        next_evolution: [],
        prev_evolution: [140],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/kabutops.gif'
    },
    {
        id: 142,
        name: 'Aerodactyl',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/142.png',
        type: ['Rock', 'Flying'],
        candy: 'Aerodactyl Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Fire', 'Ice', 'Flying', 'Bug', 'Grass', 'Fighting'],
        weaknesses: ['Fighting', 'Ground', 'Steel', 'Electric', 'Rock'],
        egg: 10,
        buddy: 5,
        next_evolution: [],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/aerodactyl.gif'
    },
    {
        id: 143,
        name: 'Snorlax',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/143.png',
        type: ['Normal'],
        candy: 'Snorlax Candy',
        candy_count: 0,
        immunes: [],
        strengths: [],
        weaknesses: ['Rock', 'Steel', 'Ghost'],
        egg: 10,
        buddy: 5,
        next_evolution: [],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/snorlax.gif'
    },
    {
        id: 144,
        name: 'Articuno',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/144.png',
        type: ['Ice', 'Flying'],
        candy: 'None',
        candy_count: 0,
        immunes: [],
        strengths: ['Grass', 'Ground', 'Flying', 'Dragon', 'Fighting', 'Bug'],
        weaknesses: ['Fire', 'Water', 'Ice', 'Steel', 'Electric', 'Rock'],
        egg: 0,
        buddy: 5,
        next_evolution: [],
        prev_evolution: [],
        location: 'Unavailable',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/articuno.gif'
    },
    {
        id: 145,
        name: 'Zapdos',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/145.png',
        type: ['Electric', 'Flying'],
        candy: 'None',
        candy_count: 0,
        immunes: [],
        strengths: ['Water', 'Flying', 'Grass', 'Fighting', 'Bug'],
        weaknesses: ['Electric', 'Grass', 'Dragon', 'Ground', 'Rock', 'Steel'],
        egg: 0,
        buddy: 5,
        next_evolution: [],
        prev_evolution: [],
        location: 'Unavailable',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/zapdos.gif'
    },
    {
        id: 146,
        name: 'Moltres',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/146.png',
        type: ['Fire', 'Flying'],
        candy: 'None',
        candy_count: 0,
        immunes: [],
        strengths: ['Grass', 'Ice', 'Bug', 'Steel', 'Fighting'],
        weaknesses: ['Fire', 'Water', 'Rock', 'Dragon', 'Electric', 'Steel'],
        egg: 0,
        buddy: 5,
        next_evolution: [],
        prev_evolution: [],
        location: 'Unavailable',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/moltres.gif'
    },
    {
        id: 147,
        name: 'Dratini',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/147.png',
        type: ['Dragon'],
        candy: 'Dratini Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Dragon'],
        weaknesses: ['Steel', 'Fairy'],
        egg: 10,
        buddy: 5,
        next_evolution: [148, 149],
        prev_evolution: [],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/dratini.gif'
    },
    {
        id: 148,
        name: 'Dragonair',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/148.png',
        type: ['Dragon'],
        candy: 'Dratini Candy',
        candy_count: '25',
        immunes: [],
        strengths: ['Dragon'],
        weaknesses: ['Steel', 'Fairy'],
        egg: 0,
        buddy: 5,
        next_evolution: [149],
        prev_evolution: [147],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/dragonair.gif'
    },
    {
        id: 149,
        name: 'Dragonite',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/149.png',
        type: ['Dragon', 'Flying'],
        candy: 'Dratini Candy',
        candy_count: '100',
        immunes: [],
        strengths: ['Dragon', 'Grass', 'Fighting', 'Bug'],
        weaknesses: ['Steel', 'Fairy', 'Electric', 'Rock'],
        egg: 0,
        buddy: 5,
        next_evolution: [],
        prev_evolution: [147, 148],
        location: '',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/dragonite.gif'
    },
    {
        id: 150,
        name: 'Mewtwo',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/150.png',
        type: ['Psychic'],
        candy: 'None',
        candy_count: 0,
        immunes: [],
        strengths: ['Fighting', 'Poison'],
        weaknesses: ['Psychic', 'Steel', 'Dark'],
        egg: 0,
        buddy: 5,
        next_evolution: [],
        prev_evolution: [],
        location: 'Unavailable',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/mewtwo.gif'
    },
    {
        id: 151,
        name: 'Mew',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/151.png',
        type: ['Psychic'],
        candy: 'None',
        candy_count: 0,
        immunes: [],
        strengths: ['Fighting', 'Poison'],
        weaknesses: ['Psychic', 'Steel', 'Dark'],
        egg: 0,
        buddy: 5,
        next_evolution: [],
        prev_evolution: [],
        location: 'Unavailable',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/mew.gif'
    },
    {
        id: 172,
        name: 'Pichu',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/172.png',
        type: ['Electric'],
        candy: 'Pikachu Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Water', 'Flying'],
        weaknesses: ['Electric', 'Grass', 'Dragon', 'Ground'],
        egg: 5,
        buddy: 1,
        next_evolution: [25, 26],
        prev_evolution: [],
        location: 'Unavailable',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/pichu.gif'
    },
    {
        id: 173,
        name: 'Cleffa',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/173.png',
        type: ['Normal'],
        candy: 'Clefairy Candy',
        candy_count: 0,
        immunes: [],
        strengths: [],
        weaknesses: ['Rock', 'Steel', 'Ghost'],
        egg: 2,
        buddy: 1,
        next_evolution: [35, 36],
        prev_evolution: [],
        location: 'Unavailable',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/cleffa.gif'
    },
    {
        id: 174,
        name: 'Igglybuff',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/174.png',
        type: ['Normal'],
        candy: 'Jigglypuff Candy',
        candy_count: 0,
        immunes: [],
        strengths: [],
        weaknesses: ['Rock', 'Steel', 'Ghost'],
        egg: 2,
        buddy: 1,
        next_evolution: [39, 40],
        prev_evolution: [],
        location: 'Unavailable',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/igglybuff.gif'
    },
    {
        id: 175,
        name: 'Togepi',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/175.png',
        type: ['Normal'],
        candy: 'Togepi Candy',
        candy_count: 0,
        immunes: [],
        strengths: [],
        weaknesses: ['Rock', 'Steel', 'Ghost'],
        egg: 5,
        buddy: 5,
        next_evolution: [176],
        prev_evolution: [],
        location: 'Unavailable',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/togepi.gif'
    },
    {
        id: 176,
        name: 'Togetic',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/176.png',
        type: ['fairy', 'Flying'],
        candy: 'Togepi Candy',
        candy_count: '50',
        immunes: [],
        strengths: ['Grass', 'Fighting', 'Dragon', 'Dark', 'Bug'],
        weaknesses: ['Fire', 'Poison', 'Steel', 'Electric', 'Rock'],
        egg: 0,
        buddy: 5,
        next_evolution: [],
        prev_evolution: [175],
        location: 'Unavailable',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/togetic.gif'
    },
    {
        id: 238,
        name: 'Smoochum',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/238.png',
        type: ['Ice', 'Psychic'],
        candy: 'Jynx Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Grass', 'Ground', 'Flying', 'Dragon', 'Fighting', 'Poison'],
        weaknesses: ['Fire', 'Water', 'Ice', 'Steel', 'Psychic', 'Dark'],
        egg: 10,
        buddy: 5,
        next_evolution: [124],
        prev_evolution: [],
        location: 'Unavailable',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/smoochum.gif'
    },
    {
        id: 239,
        name: 'Elekid',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/239.png',
        type: ['Electric'],
        candy: 'Electabuzz Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Water', 'Flying'],
        weaknesses: ['Electric', 'Grass', 'Dragon', 'Ground'],
        egg: 10,
        buddy: 5,
        next_evolution: [125],
        prev_evolution: [],
        location: 'Unavailable',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/elekid.gif'
    },
    {
        id: 240,
        name: 'Magby',
        img: 'http://www.pkparaiso.com/xy/sprites/pokemon/240.png',
        type: ['Fire'],
        candy: 'Magmar Candy',
        candy_count: 0,
        immunes: [],
        strengths: ['Grass', 'Ice', 'Bug', 'Steel'],
        weaknesses: ['Fire', 'Water', 'Rock', 'Dragon'],
        egg: 10,
        buddy: 5,
        next_evolution: [126],
        prev_evolution: [],
        location: 'Unavailable',
        gif: 'http://www.pkparaiso.com/imagenes/xy/sprites/animados/magby.gif'
    }];

var pokemonSchema = new mongoose.Schema({
    id: { type: Number, unique: true },
    name: String,
    img: String,
    gif: String,
    type: [String],
    candy: String,
    candy_count: Number,
    egg: Number,
    buddy: Number,
    multipliers: Number,
    immunes: [String],
    weaknesses: [String],
    strengths: [String],
    next_evolution: [Number],
    prev_evolution: [Number],
    location: String
});

pokemonSchema.virtual('keywords').get(function () {
    return [this.name, ("000" + this.id).slice(-3), this.type, this.egg + 'km', this.location];
});

pokemonSchema.set('toObject', {
    virtuals: true
});
pokemonSchema.set('toJSON', {
    virtuals: true
});

var PokemonDB = mongoose.model('Pokemon', pokemonSchema);
PokemonDB.collection.remove({});
PokemonDB.create(pokemonRawData, function (err) {
    if (err) {
        console.log(err);
    } else {
        PokemonDB.count({}, function (err, count) {
            if (err) console.log(err);
            console.log('%d pokemons were successfully loaded in PokemonDB.', count);
        });
    }
});

var getPokemon = function () {
    if (arguments.length === 1) {
        var callback = arguments[0];
        PokemonDB.find(function (err, pokemon) {
            if (err) callback(err);
            else callback(null, pokemon);
        });
    }
    else if (arguments.length === 2) {
        var id = arguments[0];
        var callback = arguments[1];
        PokemonDB.findOne({ 'id': id }, function (err, pokemon) {
            if (err) callback(err);
            else callback(null, pokemon);
        });
    }
};

module.exports.get = getPokemon;